//! The `go` [`CodeGenerator`] target.
//!
//! Consumes the exact same validated [`EtlDocument`] + resolved fault-tree
//! probabilities + [`AsyncApiRegistry`] every other target consumes.
//! Nothing here re-parses `.etdl`, re-validates ECEL conditions, or
//! re-evaluates fault trees. Generated Go is a thin `cgo` binding to the
//! same compiled `etdl-runtime-ffi` C ABI the Java/Python/.NET targets
//! bind to — not a reimplementation of ETDL semantics. See
//! `docs/architecture/targets.md`.
//!
//! Building this crate never requires a Go toolchain — it only emits Go
//! source text (plus a minimal `go.mod`). A Go toolchain (with `cgo`
//! enabled, the default) is needed only to *build and run* the generated
//! output, and `etdl-runtime-ffi`'s compiled shared/static library plus
//! its `include/etdl_runtime.h` header are needed to build anything that
//! touches `BranchMonitor`/`RetryPolicy`/`Condition`.
//!
//! # Untested in this environment
//!
//! Unlike the Java/Python/.NET targets (each verified end-to-end against
//! the real compiled `etdl-runtime-ffi` library in this repository's own
//! test suite), **no Go toolchain was available in the environment this
//! target was implemented in**, so none of its generated `cgo` code has
//! been compiled or run. It follows well-established, documented `cgo`
//! idioms throughout (`runtime/cgo.Handle` for passing Go state through a
//! C callback — the standard mechanism since Go 1.17; a small C shim
//! function per callback site, so cgo never has to marshal an anonymous
//! C function-pointer type; `C._Bool`, not `C.bool`, for C99 `_Bool`
//! parameters) and was reasoned through carefully, but it should be
//! verified against a real `go build` before being relied on — see
//! `etdl-target-go/tests/go_generation.rs`'s `go_build_*` tests, which
//! skip with a clear message when `go` isn't on `PATH` rather than
//! silently passing.

use etdl_compiler::{CodeGenerator, Diagnostic, GeneratedFile};
use etdl_parser::ast::{
    BackoffStrategy as AstBackoffStrategy, ChannelRef, Condition, EtlDocument, EventTree,
    MessageRef, Node,
};
use etdl_parser::asyncapi::AsyncApiRegistry;
use etdl_parser::ecel;
use std::collections::BTreeMap;

const GO_MODULE: &str = "etdlgenerated";

pub struct GoCodeGenerator {
    pub version: String,
    /// Go package name for document-specific output. `None` derives it
    /// (lowercased, no separators — Go package-naming convention) from
    /// `info.domain`.
    pub package: Option<String>,
}

impl Default for GoCodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl GoCodeGenerator {
    pub fn new() -> Self {
        GoCodeGenerator {
            version: env!("CARGO_PKG_VERSION").to_string(),
            package: None,
        }
    }

    fn resolve_package(&self, doc: &EtlDocument) -> String {
        if let Some(ref p) = self.package {
            return p.clone();
        }
        sanitize_package(&doc.info.domain)
    }
}

impl CodeGenerator for GoCodeGenerator {
    fn target_name(&self) -> &'static str {
        "go"
    }

    fn generate_all(
        &self,
        doc: &EtlDocument,
        fault_tree_probs: &BTreeMap<String, f64>,
        registry: &AsyncApiRegistry,
        stem: &str,
        _diagnostics: &mut Vec<Diagnostic>,
    ) -> Result<Vec<GeneratedFile>, String> {
        let package = self.resolve_package(doc);
        let _ = stem;

        let mut files = runtime_files();
        files.push(GeneratedFile::new("go.mod", generate_go_mod()));

        let message_refs = collect_message_refs(doc);
        if !message_refs.is_empty() {
            let mut messages_file = String::new();
            messages_file.push_str("// AUTOGENERATED BY ETDL COMPILER - DO NOT EDIT DIRECTLY\n\n");
            messages_file.push_str(&format!("package {package}\n\n"));
            for (type_name, msg_ref) in &message_refs {
                let value = registry
                    .resolve_message(doc, msg_ref)
                    .map_err(|e| format!("resolving message for '{type_name}': {e}"))?;
                messages_file.push_str(&generate_message_struct(type_name, &value));
            }
            files.push(GeneratedFile::new(
                format!("{package}/messages.go"),
                messages_file,
            ));
        }

        for tree in doc.event_trees.values() {
            let tree_id = tree_id_of(doc, tree);
            let iface_name = format!("{}Handlers", to_pascal_case(&sanitize_ident(tree_id)));
            let handler_methods = collect_handler_methods(tree);
            let msg_type = ref_to_type_name(&tree.initiating_event.message);
            let module_name = to_snake_case(&sanitize_ident(tree_id));
            files.push(GeneratedFile::new(
                format!("{package}/{module_name}_handlers.go"),
                generate_handlers_interface(&package, &iface_name, &msg_type, &handler_methods),
            ));
        }

        let workflow = generate_workflow_file(doc, &package, fault_tree_probs)?;
        files.push(GeneratedFile::new(
            format!("{package}/workflow.go"),
            workflow,
        ));

        Ok(files)
    }
}

fn tree_id_of<'a>(doc: &'a EtlDocument, tree: &EventTree) -> &'a str {
    doc.event_trees
        .iter()
        .find(|(_, t)| std::ptr::eq(*t, tree))
        .map(|(id, _)| id.as_str())
        .unwrap_or("Tree")
}

fn generate_go_mod() -> String {
    format!(
        r#"// AUTOGENERATED BY ETDL COMPILER - safe to edit (rename the module, add your own
// developer .go files/packages anywhere in this tree, add `require`
// directives for your own dependencies).
module {GO_MODULE}

go 1.21
"#
    )
}

// ---------------------------------------------------------------------
// Fixed, document-independent runtime (`etdl/runtime/*.go`)
// ---------------------------------------------------------------------

fn runtime_files() -> Vec<GeneratedFile> {
    vec![
        GeneratedFile::new("etdl/runtime/errors.go", ERRORS_GO),
        GeneratedFile::new("etdl/runtime/publisher.go", PUBLISHER_GO),
        GeneratedFile::new("etdl/runtime/native.go", NATIVE_GO),
        GeneratedFile::new("etdl/runtime/branch_monitor.go", BRANCH_MONITOR_GO),
        GeneratedFile::new("etdl/runtime/retry_policy.go", RETRY_POLICY_GO),
        GeneratedFile::new("etdl/runtime/condition.go", CONDITION_GO),
    ]
}

const ERRORS_GO: &str = r#"// Read-only ETDL runtime. DO NOT EDIT DIRECTLY.
package etdlruntime

// WorkflowError is raised for a retryable operation failure. Analogous to
// the Rust target's etdl_core::WorkflowError and the Java/Python/.NET
// targets' WorkflowError. errors.As(err, &target) works against it, since
// generated orchestration distinguishes a retryable WorkflowError from any
// other (fatal, not retried) error a handler returns.
type WorkflowError struct {
	Message string
	Cause   error
}

func (e *WorkflowError) Error() string {
	if e.Cause != nil {
		return e.Message + ": " + e.Cause.Error()
	}
	return e.Message
}

func (e *WorkflowError) Unwrap() error {
	return e.Cause
}

func NewWorkflowError(message string) *WorkflowError {
	return &WorkflowError{Message: message}
}
"#;

const PUBLISHER_GO: &str = r#"// Read-only ETDL runtime. DO NOT EDIT DIRECTLY.
package etdlruntime

// Publisher is the stable API boundary generated orchestration code calls
// into for a `consequence: send` (core spec Section 5.5.3). A developer
// supplies a concrete implementation (wiring it to a real broker/client
// and handling serialization however fits their stack); generated code
// never depends on a specific transport or JSON library. Application
// integration, not ETDL runtime machinery — unlike BranchMonitor/
// RetryPolicy/Condition, there is no native binding here: there is no
// shared "publish" semantics in the Rust runtime to delegate to.
type Publisher interface {
	Publish(channel string, payload any) error
}
"#;

/// The native-binding layer: `cgo` against `etdl-runtime-ffi`'s
/// `include/etdl_runtime.h` (the same header Go's own build links
/// against). `BranchMonitor`/`RetryPolicy`/`Condition` are thin facades
/// over this; nothing here re-implements ETDL semantics.
const NATIVE_GO: &str = r#"// Read-only ETDL runtime. DO NOT EDIT DIRECTLY.
//
// Binds to `libetdl_runtime_ffi` (built from the `etdl-runtime-ffi` Rust
// crate — see `docs/architecture/targets.md`) via cgo.
//
// Build configuration: the `#cgo` directives below link against a bare
// `etdl_runtime_ffi` library name (dynamic linking; `libetdl_runtime_ffi.a`
// exists too, for static linking — pass `-static` yourself via
// CGO_LDFLAGS if you prefer that). Point the compiler/linker at your
// build of etdl-runtime-ffi with environment variables, e.g.:
//
//	CGO_CFLAGS="-I/path/to/etdl-runtime-ffi/include" \
//	CGO_LDFLAGS="-L/path/to/target/release" \
//	LD_LIBRARY_PATH="/path/to/target/release" \
//	go build ./...
//
// (LD_LIBRARY_PATH only matters for dynamic linking, and only at *run*
// time, not build time — the linker itself finds the .so at build time via
// CGO_LDFLAGS's -L.)
package etdlruntime

/*
#cgo LDFLAGS: -letdl_runtime_ffi
#include <stdint.h>
#include <stdlib.h>
#include "etdl_runtime.h"
*/
import "C"

import "unsafe"

// Mirrors etdl-runtime-ffi's ETDL_OK / ETDL_ERR_* / ETDL_RETRY_* constants exactly.
const (
	Ok             = 0
	ErrNullHandle  = -1
	ErrInvalidArg  = -2
	RetryOk        = 0
	RetryExhausted = 1
	RetryFatal     = 2
)

// LastError reads and frees the calling thread's last native error message.
func LastError() string {
	ptr := C.etdl_last_error_message()
	if ptr == nil {
		return "(no further detail available from the native runtime)"
	}
	msg := C.GoString(ptr)
	C.etdl_string_free(ptr)
	return msg
}

func cstr(s string) *C.char {
	return C.CString(s)
}

func freeCstr(s *C.char) {
	C.free(unsafe.Pointer(s))
}

// NOTE (untested — see this crate's doc comment): converts a Go bool to
// the C99 `_Bool`/`bool` (via <stdbool.h>) etdl_runtime.h's
// `has_probability` parameters use. `C.bool` is used here as the more
// commonly seen spelling in real-world cgo code once <stdbool.h> is
// included; if a real `go build` reports it unresolved, `C._Bool` (the
// name cgo derives directly from the underlying C99 type without the
// stdbool.h macro) is the documented fallback — change every `C.bool`
// below to `C._Bool` in that case.
func goBool(b bool) C.bool {
	if b {
		return C.bool(true)
	}
	return C.bool(false)
}
"#;

/// The Go analog of `etdl_core::BranchMonitor` — not a reimplementation:
/// every method is a direct call into the same `BranchMonitor` the Rust
/// target's generated code has always used, via `etdl-runtime-ffi`.
const BRANCH_MONITOR_GO: &str = r#"// Read-only ETDL runtime. DO NOT EDIT DIRECTLY.
//
// Thin facade over the native etdl_core::BranchMonitor (via
// etdl-runtime-ffi). Owns one native handle; always Close() it (generated
// orchestration code always defers Close()) so etdl_branch_monitor_free
// runs deterministically.
package etdlruntime

/*
#include "etdl_runtime.h"
*/
import "C"

import "fmt"

type BranchMonitor struct {
	handle *C.EtdlBranchMonitor
}

func NewBranchMonitor(nodeID string) (*BranchMonitor, error) {
	cNodeID := cstr(nodeID)
	defer freeCstr(cNodeID)
	h := C.etdl_branch_monitor_new(cNodeID)
	if h == nil {
		return nil, fmt.Errorf("etdl_branch_monitor_new failed: %s", LastError())
	}
	return &BranchMonitor{handle: h}, nil
}

func (m *BranchMonitor) RecordBranch(outcome string, probability float64) error {
	cOutcome := cstr(outcome)
	defer freeCstr(cOutcome)
	rc := C.etdl_branch_monitor_record_branch(m.handle, cOutcome, C.double(probability))
	return checkRc(int(rc), "etdl_branch_monitor_record_branch")
}

// RecordSuccess: probability is nil when the operation has no linked fault tree.
func (m *BranchMonitor) RecordSuccess(operationID string, probability *float64) error {
	cOpID := cstr(operationID)
	defer freeCstr(cOpID)
	var p float64
	if probability != nil {
		p = *probability
	}
	rc := C.etdl_branch_monitor_record_success(m.handle, cOpID, C.double(p), goBool(probability != nil))
	return checkRc(int(rc), "etdl_branch_monitor_record_success")
}

// RecordFailure: probability is nil when the operation has no linked fault tree.
func (m *BranchMonitor) RecordFailure(operationID string, err error, probability *float64) error {
	cOpID := cstr(operationID)
	defer freeCstr(cOpID)
	cErrMsg := cstr(err.Error())
	defer freeCstr(cErrMsg)
	var p float64
	if probability != nil {
		p = *probability
	}
	rc := C.etdl_branch_monitor_record_failure(m.handle, cOpID, cErrMsg, C.double(p), goBool(probability != nil))
	return checkRc(int(rc), "etdl_branch_monitor_record_failure")
}

func (m *BranchMonitor) Close() {
	if m.handle != nil {
		C.etdl_branch_monitor_free(m.handle)
		m.handle = nil
	}
}

func checkRc(rc int, call string) error {
	if rc != Ok {
		return fmt.Errorf("%s failed (code %d): %s", call, rc, LastError())
	}
	return nil
}
"#;

/// The Go analog of `etdl_core::retry::RetryPolicy` — the attempt-count
/// and backoff *sequence* are computed once, in Rust
/// (`etdl_retry_policy_execute`'s native loop), via a `runtime/cgo.Handle`
/// (the standard, documented mechanism for passing Go state through a C
/// callback since Go 1.17) bound to a Go closure through a small C shim
/// function — cgo cannot directly marshal a Go `//export`ed function into
/// an anonymous (non-`typedef`'d) C function-pointer parameter, so the
/// shim (`etdl_retry_policy_execute_shim`, pure C, calling the real
/// function with the exported Go trampoline as a plain named argument)
/// sidesteps that entirely. Per-attempt timeout enforcement stays here
/// (see `docs/architecture/targets.md`'s "Ownership model": no FFI
/// boundary can safely cancel foreign code mid-flight) using a goroutine +
/// channel + `time.After` — note the timed-out goroutine itself cannot be
/// forcibly killed either; only the *retry loop* moves on.
const RETRY_POLICY_GO: &str = r#"// Read-only ETDL runtime. DO NOT EDIT DIRECTLY.
package etdlruntime

/*
#include <stdint.h>
#include "etdl_runtime.h"

extern int32_t goEtdlRetryTrampoline(void* user_data, uint32_t attempt);

static int32_t etdl_retry_policy_execute_shim(const EtdlRetryPolicy* handle, void* user_data, uint32_t* out_attempts_used) {
    return etdl_retry_policy_execute(handle, goEtdlRetryTrampoline, user_data, out_attempts_used);
}
*/
import "C"

import (
	"errors"
	"fmt"
	"runtime/cgo"
	"time"
	"unsafe"
)

type BackoffStrategy int32

const (
	BackoffFixed       BackoffStrategy = 0
	BackoffExponential BackoffStrategy = 1
)

type RetryPolicy struct {
	handle *C.EtdlRetryPolicy
}

func NewRetryPolicy(maxAttempts uint32, backoffMs uint64, strategy BackoffStrategy) (*RetryPolicy, error) {
	h := C.etdl_retry_policy_new(C.uint32_t(maxAttempts), C.uint64_t(backoffMs), C.int32_t(strategy))
	if h == nil {
		return nil, fmt.Errorf("etdl_retry_policy_new failed: %s", LastError())
	}
	return &RetryPolicy{handle: h}, nil
}

func (r *RetryPolicy) Close() {
	if r.handle != nil {
		C.etdl_retry_policy_free(r.handle)
		r.handle = nil
	}
}

// retryCallback is what a Go attempt reports back to the native retry
// loop: 0 success, positive retryable, negative fatal — exactly
// etdl_retry_policy_execute's documented callback contract.
type retryCallback func(attempt uint32) int32

//export goEtdlRetryTrampoline
func goEtdlRetryTrampoline(userData unsafe.Pointer, attempt C.uint32_t) C.int32_t {
	h := cgo.Handle(uintptr(userData))
	cb := h.Value().(retryCallback)
	return C.int32_t(cb(uint32(attempt)))
}

type attemptResult struct {
	value any
	err   error
}

// Execute runs op, retrying per this policy's configured attempts/backoff
// (computed once, authoritatively, in Rust). A *WorkflowError op returns
// is retryable; any other error is fatal (not retried) — mirroring every
// other target's binding. op's own panic is caught here and converted to
// a fatal error — it never crosses the native call.
func (r *RetryPolicy) Execute(op func() (any, error), timeout time.Duration) (any, error) {
	var result any
	var checkedErr error
	var fatalErr error

	cb := retryCallback(func(attempt uint32) int32 {
		ch := make(chan attemptResult, 1)
		go func() {
			defer func() {
				if p := recover(); p != nil {
					ch <- attemptResult{nil, fmt.Errorf("panic in operation: %v", p)}
				}
			}()
			v, err := op()
			ch <- attemptResult{v, err}
		}()

		var res attemptResult
		if timeout > 0 {
			select {
			case res = <-ch:
			case <-time.After(timeout):
				checkedErr = fmt.Errorf("operation timed out after %s", timeout)
				return 1
			}
		} else {
			res = <-ch
		}

		if res.err == nil {
			result = res.value
			return 0
		}
		var we *WorkflowError
		if errors.As(res.err, &we) {
			checkedErr = res.err
			return 1
		}
		fatalErr = res.err
		return -1
	})

	handle := cgo.NewHandle(cb)
	defer handle.Delete()

	var attemptsUsed C.uint32_t
	rc := C.etdl_retry_policy_execute_shim(r.handle, unsafe.Pointer(uintptr(handle)), &attemptsUsed)

	switch int32(rc) {
	case RetryOk:
		return result, nil
	case RetryFatal:
		if fatalErr != nil {
			return nil, fatalErr
		}
		return nil, fmt.Errorf("retry failed fatally: %s", LastError())
	default: // RetryExhausted
		if checkedErr != nil {
			return nil, checkedErr
		}
		return nil, fmt.Errorf("retry exhausted: %s", LastError())
	}
}
"#;

/// The Go analog of `etdl_core::condition::{contains, matches}` — ECEL
/// `in`/`matches` semantics stay in Rust; this facade only marshals
/// values to/from the JSON text `etdl_condition_contains` expects, using
/// `encoding/json` (Go's standard library — no extra module dependency).
const CONDITION_GO: &str = r#"// Read-only ETDL runtime. DO NOT EDIT DIRECTLY.
//
// ECEL (core spec Section 6) `in`/`matches` operators lower to these
// helpers, delegating to the native etdl_core::condition module (via
// etdl-runtime-ffi) — so a `matches` regex or an `in` membership check
// behaves byte-for-byte identically no matter which target (Rust, Java,
// Python, Go, .NET) evaluates it.
package etdlruntime

/*
#include "etdl_runtime.h"
*/
import "C"

import (
	"encoding/json"
	"fmt"
)

func Matches(value, pattern string) (bool, error) {
	cValue := cstr(value)
	defer freeCstr(cValue)
	cPattern := cstr(pattern)
	defer freeCstr(cPattern)
	rc := C.etdl_condition_matches(cValue, cPattern)
	if rc < 0 {
		return false, fmt.Errorf("etdl_condition_matches: %s", LastError())
	}
	return rc == 1, nil
}

func Contains(haystack any, needle any) (bool, error) {
	needleJSON, err := json.Marshal(needle)
	if err != nil {
		return false, fmt.Errorf("marshal needle: %w", err)
	}
	haystackJSON, err := json.Marshal(haystack)
	if err != nil {
		return false, fmt.Errorf("marshal haystack: %w", err)
	}
	cNeedle := cstr(string(needleJSON))
	defer freeCstr(cNeedle)
	cHaystack := cstr(string(haystackJSON))
	defer freeCstr(cHaystack)
	rc := C.etdl_condition_contains(cNeedle, cHaystack)
	if rc < 0 {
		return false, fmt.Errorf("etdl_condition_contains: %s", LastError())
	}
	return rc == 1, nil
}
"#;

// ---------------------------------------------------------------------
// Message structs
// ---------------------------------------------------------------------

fn collect_message_refs(doc: &EtlDocument) -> BTreeMap<String, MessageRef> {
    let mut refs: BTreeMap<String, MessageRef> = BTreeMap::new();
    let note = |m: &MessageRef, refs: &mut BTreeMap<String, MessageRef>| {
        let name = ref_to_type_name(m);
        refs.entry(name).or_insert_with(|| m.clone());
    };

    for tree in doc.event_trees.values() {
        note(&tree.initiating_event.message, &mut refs);
        for node in tree.nodes.values() {
            match node {
                Node::Operation(op) => {
                    if let Some(ref m) = op.emits {
                        note(m, &mut refs);
                    }
                }
                Node::Consequence(cons) => {
                    if let Some(ref m) = cons.message {
                        note(m, &mut refs);
                    }
                }
                _ => {}
            }
        }
    }

    if let Some(ref fault_trees) = doc.fault_trees {
        for ft in fault_trees.values() {
            if let Some(ref m) = ft.top_event.message {
                note(m, &mut refs);
            }
            for be in ft.basic_events.values() {
                if let Some(ref m) = be.message {
                    note(m, &mut refs);
                }
            }
        }
    }

    refs
}

fn ref_to_type_name(msg_ref: &MessageRef) -> String {
    let pointer = match msg_ref {
        MessageRef::External(r) => &r.pointer,
        MessageRef::Internal(r) => &r.pointer,
    };
    extract_last_segment(pointer)
}

fn extract_last_segment(pointer: &str) -> String {
    let last = pointer.rsplit('/').next().unwrap_or("Unknown");
    to_pascal_case(last)
}

fn generate_message_struct(type_name: &str, message: &serde_json::Value) -> String {
    let payload_type_name = format!("{type_name}Payload");
    let payload_schema = message.get("payload").cloned().unwrap_or(serde_json::Value::Null);

    let mut nested = String::new();
    let payload_go_type = schema_to_go_type(&payload_type_name, &payload_schema, &mut nested);

    let mut out = String::new();
    out.push_str(&nested);
    out.push_str(&format!("type {type_name} struct {{\n"));
    out.push_str(&format!("\tPayload {payload_go_type} `json:\"payload\"`\n"));
    out.push_str("\tHeaders map[string]any `json:\"headers,omitempty\"`\n");
    out.push_str("}\n\n");
    out
}

/// Go analog of the other targets' struct/record/dataclass generators. Go
/// struct fields have no ordering constraint (unlike Python's
/// `@dataclass`/C#'s positional `record`), so — unlike those two targets —
/// schema property order is kept as-is; only the "optional field becomes a
/// pointer type" convention (Go's idiomatic nullable) differs per target.
fn generate_struct_from_schema(name: &str, schema: &serde_json::Value, output: &mut String) {
    let Some(properties) = schema.get("properties").and_then(|p| p.as_object()) else {
        return;
    };

    let required: std::collections::BTreeSet<&str> = schema
        .get("required")
        .and_then(|r| r.as_array())
        .map(|arr| arr.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default();

    let mut nested = String::new();
    let mut fields = String::new();

    for (field_name, field_schema) in properties {
        let pascal = to_pascal_case(field_name);
        let nested_type_name = format!("{name}{pascal}");
        let is_required = required.contains(field_name.as_str());
        let go_type = schema_to_go_type(&nested_type_name, field_schema, &mut nested);
        // Deliberately never pointer-wraps an optional field (unlike the
        // Python/C#/Java targets' nullable equivalents): ECEL condition
        // codegen (`build_path_expression`/`append_segment`) generates
        // plain field-access expressions with no schema/type awareness of
        // which fields are optional, so a condition comparing or
        // `range`-ing over an optional field must see a directly usable
        // value — a `*string`/`*[]T` would need an explicit nil-check/
        // deref at every access site codegen doesn't (and, without
        // threading schema types through condition codegen, safely can't)
        // insert. The tradeoff: a Go struct can't distinguish "field
        // absent" from "field present with its zero value" the way the
        // other targets' nullable types can — documented in
        // docs/architecture/targets.md's Go section.
        let omit = if is_required { "" } else { ",omitempty" };
        fields.push_str(&format!(
            "\t{pascal} {go_type} `json:\"{field_name}{omit}\"`\n"
        ));
    }

    output.push_str(&nested);
    output.push_str(&format!("type {name} struct {{\n{fields}}}\n\n"));
}

fn schema_to_go_type(candidate_name: &str, schema: &serde_json::Value, nested: &mut String) -> String {
    match schema.get("type").and_then(|t| t.as_str()) {
        Some("string") => "string".to_string(),
        Some("integer") => "int64".to_string(),
        Some("number") => "float64".to_string(),
        Some("boolean") => "bool".to_string(),
        Some("array") => {
            let item_type = match schema.get("items") {
                Some(items_schema) => {
                    schema_to_go_type(&format!("{candidate_name}Item"), items_schema, nested)
                }
                None => "any".to_string(),
            };
            format!("[]{item_type}")
        }
        Some("object") => {
            if schema.get("properties").is_some() {
                generate_struct_from_schema(candidate_name, schema, nested);
                candidate_name.to_string()
            } else {
                "map[string]any".to_string()
            }
        }
        _ => "any".to_string(),
    }
}

// ---------------------------------------------------------------------
// Handler interfaces (one per event tree — the user-editable boundary)
// ---------------------------------------------------------------------

fn collect_handler_methods(tree: &EventTree) -> Vec<String> {
    let mut seen = std::collections::BTreeSet::new();
    let mut methods = Vec::new();
    for node in tree.nodes.values() {
        if let Node::Operation(op) = node {
            let name = to_pascal_case(&op.handler);
            if seen.insert(name.clone()) {
                methods.push(name);
            }
        }
    }
    methods
}

fn generate_handlers_interface(package: &str, iface_name: &str, msg_type: &str, methods: &[String]) -> String {
    let mut out = String::new();
    out.push_str("// AUTOGENERATED BY ETDL COMPILER - DO NOT EDIT DIRECTLY\n");
    out.push_str("// Implement this interface in your own (never regenerated) file; the\n");
    out.push_str("// generated orchestration calls through it and never the other way around.\n");
    out.push_str(&format!("package {package}\n\n"));
    out.push_str(&format!("type {iface_name} interface {{\n"));
    for method in methods {
        out.push_str(&format!("\t{method}(message {msg_type}) (any, error)\n"));
    }
    out.push_str("}\n");
    out
}

// ---------------------------------------------------------------------
// Workflow orchestration
// ---------------------------------------------------------------------

fn generate_workflow_file(
    doc: &EtlDocument,
    package: &str,
    fault_tree_probs: &BTreeMap<String, f64>,
) -> Result<String, String> {
    let mut out = String::new();
    out.push_str("// AUTOGENERATED BY ETDL COMPILER - DO NOT EDIT DIRECTLY\n\n");
    out.push_str(&format!("package {package}\n\n"));

    // `time` is only used by a retry-policy operation's timeout
    // (`{n}*time.Second`) — Go errors on an unused import, so a document
    // with no retried operations anywhere (e.g. a barrier-only tree) must
    // not import it at all.
    let any_retry = doc
        .event_trees
        .values()
        .flat_map(|t| t.nodes.values())
        .any(|n| matches!(n, Node::Operation(op) if op.retry_policy.is_some()));

    out.push_str("import (\n");
    out.push_str(&format!("\tetdlruntime \"{GO_MODULE}/etdl/runtime\"\n"));
    if any_retry {
        out.push_str("\t\"time\"\n");
    }
    out.push_str(")\n\n");

    // ECEL `in`/`matches` (core spec Section 6) lower to a native call
    // returning `(bool, error)` (Go's idiomatic error handling), but a
    // barrier condition needs a plain `bool` usable directly inside `if
    // <cond> {` — these wrap that, panicking on the (expected-never, since
    // ECEL conditions are already type-checked at compile time) error
    // case, matching the `regexp.MustCompile`-style "this cannot fail
    // given how it's called" Go idiom.
    out.push_str("func mustMatches(value, pattern string) bool {\n");
    out.push_str("\tok, err := etdlruntime.Matches(value, pattern)\n");
    out.push_str("\tif err != nil {\n\t\tpanic(err)\n\t}\n\treturn ok\n}\n\n");
    out.push_str("func mustContains(haystack any, needle any) bool {\n");
    out.push_str("\tok, err := etdlruntime.Contains(haystack, needle)\n");
    out.push_str("\tif err != nil {\n\t\tpanic(err)\n\t}\n\treturn ok\n}\n\n");

    out.push_str(&generate_fault_tree_constants(doc, fault_tree_probs));

    for tree in doc.event_trees.values() {
        let function = generate_event_tree_function(doc, tree, fault_tree_probs)?;
        out.push_str(&function);
        out.push('\n');
    }

    Ok(out)
}

fn generate_fault_tree_constants(doc: &EtlDocument, fault_tree_probs: &BTreeMap<String, f64>) -> String {
    let mut output = String::new();
    for tree in doc.event_trees.values() {
        for (node_id, node) in &tree.nodes {
            if let Node::Operation(op) = node {
                if let Some(ref ps) = op.on_failure_probability_source {
                    if let Some((ft_id, prob)) = find_fault_tree_prob(ps, fault_tree_probs) {
                        output.push_str(&format!(
                            "// Computed from faultTrees.{ft_id}.topEvent at build time (Section 5.16)\n"
                        ));
                        let const_name = to_pascal_case(&format!("{node_id}_failure_probability"));
                        output.push_str(&format!("const {const_name} = {prob:.6}\n\n"));
                    }
                }
            }
        }
    }
    output
}

fn find_fault_tree_prob(
    ps: &etdl_parser::ast::InternalRef,
    fault_tree_probs: &BTreeMap<String, f64>,
) -> Option<(String, f64)> {
    let ft_id = extract_ft_id(&ps.pointer);
    fault_tree_probs.get(&ft_id).map(|&v| (ft_id.clone(), v))
}

fn extract_ft_id(pointer: &str) -> String {
    pointer
        .trim_start_matches("#/faultTrees/")
        .trim_end_matches("/topEvent")
        .to_string()
}

fn generate_event_tree_function(
    doc: &EtlDocument,
    tree: &EventTree,
    fault_tree_probs: &BTreeMap<String, f64>,
) -> Result<String, String> {
    let mut out = String::new();

    let tree_id = tree_id_of(doc, tree);
    let iface_name = format!("{}Handlers", to_pascal_case(&sanitize_ident(tree_id)));
    let function_name = format!("Handle{}", to_pascal_case(&sanitize_ident(&tree.initiating_event.id)));
    let msg_type = ref_to_type_name(&tree.initiating_event.message);

    out.push_str(&format!(
        "func {function_name}(message {msg_type}, publisher etdlruntime.Publisher, handlers {iface_name}) error {{\n"
    ));

    let first_barrier = find_first_barrier(tree);
    let monitor_name = first_barrier.map(to_camel_case).unwrap_or_else(|| "monitor".to_string());
    out.push_str(&format!(
        "\t{monitor_name}, err := etdlruntime.NewBranchMonitor(\"{}\")\n",
        first_barrier.unwrap_or("root")
    ));
    out.push_str("\tif err != nil {\n\t\treturn err\n\t}\n");
    out.push_str(&format!("\tdefer {monitor_name}.Close()\n\n"));

    let start_node_id = &tree.initiating_event.next;
    let body = generate_node_code(doc, tree, start_node_id, 1, fault_tree_probs, &monitor_name)?;
    out.push_str(&body);

    out.push_str("}\n");
    Ok(out)
}

fn find_first_barrier(tree: &EventTree) -> Option<&str> {
    let mut current = &tree.initiating_event.next;
    loop {
        match tree.nodes.get(current.as_str()) {
            Some(Node::Barrier(_)) => return Some(current.as_str()),
            Some(Node::Operation(op)) => current = &op.next,
            Some(Node::Consequence(_)) => return None,
            None => return None,
        }
    }
}

/// Every path this (and the functions it calls) generates always ends in
/// a `return` statement — required so the enclosing Go function (declared
/// `... error`) always compiles regardless of how deeply barriers/
/// operations nest, since Go (unlike Java/Python/C#, which tolerate a
/// function body that "falls off the end" of a void method) requires
/// every path through a function with a return type to explicitly return.
fn generate_node_code(
    doc: &EtlDocument,
    tree: &EventTree,
    node_id: &str,
    depth: usize,
    fault_tree_probs: &BTreeMap<String, f64>,
    monitor_name: &str,
) -> Result<String, String> {
    let node = tree
        .nodes
        .get(node_id)
        .ok_or_else(|| format!("node '{node_id}' not found"))?;

    match node {
        Node::Barrier(barrier) => {
            generate_barrier_code(tree, node_id, barrier, depth, doc, fault_tree_probs, monitor_name)
        }
        Node::Operation(op) => {
            generate_operation_code(tree, node_id, op, depth, doc, fault_tree_probs, monitor_name)
        }
        Node::Consequence(cons) => generate_consequence_code(cons, depth),
    }
}

fn generate_barrier_code(
    tree: &EventTree,
    node_id: &str,
    barrier: &etdl_parser::ast::Barrier,
    depth: usize,
    doc: &EtlDocument,
    fault_tree_probs: &BTreeMap<String, f64>,
    monitor_name: &str,
) -> Result<String, String> {
    let indent = "\t".repeat(depth);
    let mut output = String::new();
    let mut ends_with_default = false;

    for (i, branch) in barrier.branches.iter().enumerate() {
        let is_default = branch.condition == Condition::Default;
        if is_default {
            ends_with_default = true;
        }

        if i == 0 {
            if is_default {
                emit_branch_record(&indent, monitor_name, branch, node_id, fault_tree_probs, &mut output);
                let body = generate_node_code(doc, tree, &branch.next, depth, fault_tree_probs, monitor_name)?;
                output.push_str(&body);
                break;
            }
            let cond = condition_to_go_code(&branch.condition);
            output.push_str(&format!("{indent}if {cond} {{\n"));
        } else if is_default {
            output.push_str(&format!("{indent}}} else {{\n"));
        } else {
            let cond = condition_to_go_code(&branch.condition);
            output.push_str(&format!("{indent}}} else if {cond} {{\n"));
        }

        if !is_default || i > 0 {
            emit_branch_record(&format!("{indent}\t"), monitor_name, branch, node_id, fault_tree_probs, &mut output);
            let body = generate_node_code(doc, tree, &branch.next, depth + 1, fault_tree_probs, monitor_name)?;
            output.push_str(&body);
        }
    }

    if !(barrier.branches.len() == 1 && ends_with_default) {
        if ends_with_default {
            output.push_str(&format!("{indent}}}\n"));
        } else {
            // No `default` branch declared: emit a defensive fallthrough so
            // every path still returns (Go requires it; ETDL's own
            // validation, not this target, is responsible for whether an
            // undeclared-default barrier is otherwise well-formed).
            output.push_str(&format!("{indent}}} else {{\n"));
            output.push_str(&format!(
                "{indent}\treturn etdlruntime.NewWorkflowError(\"no barrier branch matched for node \\\"{node_id}\\\"\")\n"
            ));
            output.push_str(&format!("{indent}}}\n"));
        }
    }

    Ok(output)
}

fn emit_branch_record(
    indent: &str,
    monitor_name: &str,
    branch: &etdl_parser::ast::Branch,
    node_id: &str,
    fault_tree_probs: &BTreeMap<String, f64>,
    output: &mut String,
) {
    if let Some(p) = get_branch_prob(branch, node_id, fault_tree_probs) {
        output.push_str(&format!(
            "{indent}if err := {monitor_name}.RecordBranch(\"{}\", {p:.6}); err != nil {{\n",
            branch.outcome
        ));
        output.push_str(&format!("{indent}\treturn err\n"));
        output.push_str(&format!("{indent}}}\n"));
    }
}

fn get_branch_prob(
    branch: &etdl_parser::ast::Branch,
    _node_id: &str,
    fault_tree_probs: &BTreeMap<String, f64>,
) -> Option<f64> {
    if let Some(ref ps) = branch.probability_source {
        let ft_id = extract_ft_id(&ps.pointer);
        return fault_tree_probs.get(&ft_id).copied();
    }
    branch.effective_probability()
}

fn generate_operation_code(
    tree: &EventTree,
    node_id: &str,
    op: &etdl_parser::ast::Operation,
    depth: usize,
    doc: &EtlDocument,
    fault_tree_probs: &BTreeMap<String, f64>,
    monitor_name: &str,
) -> Result<String, String> {
    let indent = "\t".repeat(depth);
    let mut output = String::new();

    let handler_name = to_pascal_case(&op.handler);
    let timeout_s = op.timeout_ms.unwrap_or(5000) as f64 / 1000.0;

    // Suffixes every local this operation declares in the *enclosing*
    // scope (not the ones already self-scoped by an `if x := ...; ...`
    // init clause) with the node id — `op.next` chaining straight into
    // another Operation node (rather than through a nested barrier/
    // consequence block) would otherwise redeclare `_result`/`opErr`/
    // `retry` a second time in the very same Go scope, which is a compile
    // error ("no new variables on left side of :="), not merely a shadow,
    // unlike Java/Python/C#.
    let suffix = to_pascal_case(&sanitize_ident(node_id));
    let result_var = format!("result{suffix}");
    let op_err_var = format!("opErr{suffix}");
    let retry_var = format!("retry{suffix}");
    let retry_err_var = format!("retryErr{suffix}");

    if let Some(ref retry) = op.retry_policy {
        let strategy = match retry.backoff_strategy.as_ref().unwrap_or(&AstBackoffStrategy::Fixed) {
            AstBackoffStrategy::Exponential => "etdlruntime.BackoffExponential",
            AstBackoffStrategy::Fixed => "etdlruntime.BackoffFixed",
        };
        output.push_str(&format!(
            "{indent}{retry_var}, {retry_err_var} := etdlruntime.NewRetryPolicy({}, {}, {strategy})\n",
            retry.max_attempts, retry.backoff_ms
        ));
        output.push_str(&format!(
            "{indent}if {retry_err_var} != nil {{\n{indent}\treturn {retry_err_var}\n{indent}}}\n"
        ));
        output.push_str(&format!("{indent}defer {retry_var}.Close()\n"));
        output.push_str(&format!(
            "{indent}{result_var}, {op_err_var} := {retry_var}.Execute(func() (any, error) {{ return handlers.{handler_name}(message) }}, {timeout_s}*time.Second)\n"
        ));
    } else {
        output.push_str(&format!(
            "{indent}{result_var}, {op_err_var} := handlers.{handler_name}(message)\n"
        ));
    }

    // Go errors ("declared and not used") if `op.next` turns out to be a
    // `terminate` consequence or another node that never actually
    // reaches `{result_var}` — unlike Java/Python/C#, where a locally
    // unused value is merely a lint warning, not a compile error. This
    // unconditional no-op read keeps it "used" regardless of what the
    // branches below do with it.
    output.push_str(&format!("{indent}_ = {result_var}\n"));

    output.push_str(&format!("{indent}if {op_err_var} != nil {{\n"));

    if let Some(ref ps) = op.on_failure_probability_source {
        let const_name = to_pascal_case(&format!("{node_id}_failure_probability"));
        let prob_exists = find_fault_tree_prob(ps, fault_tree_probs).is_some();
        if prob_exists {
            output.push_str(&format!(
                "{indent}\tp := {const_name}\n{indent}\tif err := {monitor_name}.RecordFailure(\"{node_id}\", {op_err_var}, &p); err != nil {{\n{indent}\t\treturn err\n{indent}\t}}\n"
            ));
        } else {
            output.push_str(&format!(
                "{indent}\tif err := {monitor_name}.RecordFailure(\"{node_id}\", {op_err_var}, nil); err != nil {{\n{indent}\t\treturn err\n{indent}\t}}\n"
            ));
        }
    }

    if let Some(ref on_failure_id) = op.on_failure {
        match tree.nodes.get(on_failure_id) {
            Some(Node::Consequence(cons)) => {
                emit_send(cons, "message", &format!("{indent}\t"), &mut output);
            }
            _ => {
                let body = generate_node_code(doc, tree, on_failure_id, depth + 1, fault_tree_probs, monitor_name)?;
                output.push_str(&body);
            }
        }
    } else {
        output.push_str(&format!("{indent}\treturn {op_err_var}\n"));
    }
    output.push_str(&format!("{indent}}}\n"));

    if op.on_failure.is_some() {
        if let Some(ref ps) = op.on_failure_probability_source {
            let const_name = to_pascal_case(&format!("{node_id}_failure_probability"));
            let prob_exists = find_fault_tree_prob(ps, fault_tree_probs).is_some();
            if prob_exists {
                let prob_var = format!("prob{suffix}");
                output.push_str(&format!(
                    "{indent}{prob_var} := {const_name}\n{indent}if err := {monitor_name}.RecordSuccess(\"{node_id}\", &{prob_var}); err != nil {{\n{indent}\treturn err\n{indent}}}\n"
                ));
            } else {
                output.push_str(&format!(
                    "{indent}if err := {monitor_name}.RecordSuccess(\"{node_id}\", nil); err != nil {{\n{indent}\treturn err\n{indent}}}\n"
                ));
            }
        }
    }

    let next_node = tree.nodes.get(&op.next);
    match next_node {
        Some(Node::Consequence(cons)) => {
            emit_send(cons, &result_var, &indent, &mut output);
        }
        Some(_) => {
            let body = generate_node_code(doc, tree, &op.next, depth, fault_tree_probs, monitor_name)?;
            output.push_str(&body);
        }
        None => {
            output.push_str(&format!("{indent}return nil\n"));
        }
    }

    Ok(output)
}

fn emit_send(cons: &etdl_parser::ast::Consequence, payload_expr: &str, indent: &str, output: &mut String) {
    match cons.consequence_operation {
        etdl_parser::ast::ConsequenceOperation::Send => {
            if let Some(ref channel_ref) = cons.channel {
                let channel_name = channel_ref_name(channel_ref);
                output.push_str(&format!(
                    "{indent}return publisher.Publish(\"{channel_name}\", {payload_expr})\n"
                ));
                return;
            }
            output.push_str(&format!("{indent}return nil\n"));
        }
        etdl_parser::ast::ConsequenceOperation::Terminate => {
            output.push_str(&format!("{indent}return nil\n"));
        }
    }
}

fn generate_consequence_code(cons: &etdl_parser::ast::Consequence, depth: usize) -> Result<String, String> {
    let indent = "\t".repeat(depth);
    let mut output = String::new();
    emit_send(cons, "message", &indent, &mut output);
    Ok(output)
}

fn channel_ref_name(channel_ref: &ChannelRef) -> String {
    match channel_ref {
        ChannelRef::External(ext_ref) => extract_last_segment(&ext_ref.pointer),
        ChannelRef::Bare(name) => name.clone(),
    }
}

// ---------------------------------------------------------------------
// ECEL condition -> Go
// ---------------------------------------------------------------------

fn condition_to_go_code(condition: &Condition) -> String {
    match condition {
        Condition::Default => "true".to_string(),
        Condition::Comparison(cmp) => {
            use ecel::Comparator as C;
            match cmp.op {
                C::In => {
                    let left = path_or_literal(&cmp.left);
                    let right = array_or_literal(&cmp.right);
                    format!("mustContains({right}, {left})")
                }
                C::Matches => {
                    let left = operand_to_path_expr_or_literal(&cmp.left);
                    let right = literal_to_val_str(&literal_of(&cmp.right));
                    format!("mustMatches({left}, {right})")
                }
                _ => {
                    let (left_path, has_wildcard) = build_path_expression(&cmp.left);
                    let right = operand_to_val_str(&cmp.right);
                    let op = comparator_str(&cmp.op);

                    if has_wildcard {
                        // An immediately-invoked func literal ranging over
                        // the (concretely typed) slice — `item`'s type is
                        // inferred by `range` from the slice element type,
                        // so this needs no generics or type-name tracking,
                        // unlike a hypothetical `allMatch[T any](...)`
                        // helper would.
                        format!(
                            "func() bool {{ for _, item := range {} {{ if !(item{} {} {}) {{ return false }} }}; return true }}()",
                            left_path.path_prefix, left_path.remaining_path, op, right
                        )
                    } else {
                        let l = if left_path.path_prefix.is_empty() && left_path.remaining_path.is_empty() {
                            operand_to_val_str(&cmp.left)
                        } else {
                            left_path.path_prefix + &left_path.remaining_path
                        };
                        let r = if right.is_empty() { operand_to_path_expr(&cmp.right) } else { right };
                        format!("{l} {op} {r}")
                    }
                }
            }
        }
    }
}

fn path_or_literal(operand: &ecel::Operand) -> String {
    match operand {
        ecel::Operand::Path(_) => operand_to_path_expr(operand),
        ecel::Operand::Literal(lit) => literal_to_val_str(lit),
    }
}

fn array_or_literal(operand: &ecel::Operand) -> String {
    match operand {
        ecel::Operand::Path(_) => operand_to_path_expr(operand),
        ecel::Operand::Literal(lit) => literal_to_val_str(lit),
    }
}

fn operand_to_path_expr_or_literal(operand: &ecel::Operand) -> String {
    match operand {
        ecel::Operand::Path(_) => operand_to_path_expr(operand),
        ecel::Operand::Literal(lit) => literal_to_val_str(lit),
    }
}

fn literal_of(operand: &ecel::Operand) -> ecel::Literal {
    match operand {
        ecel::Operand::Literal(lit) => lit.clone(),
        ecel::Operand::Path(_) => ecel::Literal::String(String::new()),
    }
}

struct PathParts {
    path_prefix: String,
    remaining_path: String,
}

/// Go analog of the other targets' path-expression builder. Segments
/// render as PascalCase field access (`.Field`) — generated `struct`
/// fields are exported (capitalized), matching Go's requirement that
/// `encoding/json` can only see exported fields — and `Index`/`QuotedKey`
/// segments render as `[...]` subscripting (works on both `[]T` and
/// `map[string]any` directly).
fn build_path_expression(operand: &ecel::Operand) -> (PathParts, bool) {
    match operand {
        ecel::Operand::Path(path_expr) => {
            let segments = &path_expr.segments;
            let mut pre_wildcard = Vec::new();
            let mut post_wildcard = Vec::new();
            let mut has_wildcard = false;

            for (i, seg) in segments.iter().enumerate() {
                if i == 0 {
                    continue;
                }
                if has_wildcard {
                    post_wildcard.push(seg.clone());
                } else if matches!(seg, ecel::PathSegment::Wildcard) {
                    has_wildcard = true;
                } else {
                    pre_wildcard.push(seg.clone());
                }
            }

            let mut prefix = String::from("message");
            for seg in &pre_wildcard {
                append_segment(&mut prefix, seg);
            }

            let mut suffix = String::new();
            for seg in &post_wildcard {
                append_segment(&mut suffix, seg);
            }

            (
                PathParts { path_prefix: prefix, remaining_path: suffix },
                has_wildcard,
            )
        }
        ecel::Operand::Literal(_) => (
            PathParts { path_prefix: String::new(), remaining_path: String::new() },
            false,
        ),
    }
}

fn append_segment(out: &mut String, seg: &ecel::PathSegment) {
    match seg {
        ecel::PathSegment::Field(name) => {
            out.push('.');
            out.push_str(&to_pascal_case(name));
        }
        ecel::PathSegment::Index(idx) => {
            out.push_str(&format!("[{idx}]"));
        }
        ecel::PathSegment::QuotedKey(name) => {
            out.push_str(&format!("[\"{name}\"]"));
        }
        _ => {}
    }
}

fn operand_to_path_expr(operand: &ecel::Operand) -> String {
    match operand {
        ecel::Operand::Path(path) => {
            let mut out = String::from("message");
            for seg in path.segments.iter().skip(1) {
                if matches!(seg, ecel::PathSegment::Wildcard) {
                    continue;
                }
                append_segment(&mut out, seg);
            }
            out
        }
        ecel::Operand::Literal(_) => String::new(),
    }
}

fn operand_to_val_str(operand: &ecel::Operand) -> String {
    match operand {
        ecel::Operand::Path(_) => "".to_string(),
        ecel::Operand::Literal(lit) => literal_to_val_str(lit),
    }
}

fn literal_to_val_str(lit: &ecel::Literal) -> String {
    match lit {
        ecel::Literal::Number(n) => n.to_string(),
        ecel::Literal::String(s) => format!("\"{s}\""),
        ecel::Literal::Bool(b) => b.to_string(),
        ecel::Literal::Null => "nil".to_string(),
        ecel::Literal::Array(items) => {
            let inner: Vec<String> = items.iter().map(literal_to_val_str).collect();
            format!("[]any{{ {} }}", inner.join(", "))
        }
    }
}

fn comparator_str(op: &ecel::Comparator) -> &str {
    match op {
        ecel::Comparator::Eq => "==",
        ecel::Comparator::Neq => "!=",
        ecel::Comparator::Gte => ">=",
        ecel::Comparator::Lte => "<=",
        ecel::Comparator::Gt => ">",
        ecel::Comparator::Lt => "<",
        ecel::Comparator::In => "in",
        ecel::Comparator::Matches => "matches",
    }
}

// ---------------------------------------------------------------------
// Naming helpers
// ---------------------------------------------------------------------

fn sanitize_package(domain: &str) -> String {
    let lower: String = domain.chars().filter(|c| c.is_ascii_alphanumeric()).collect::<String>().to_lowercase();
    if lower.is_empty() {
        "etdlgenerated".to_string()
    } else {
        lower
    }
}

fn sanitize_ident(s: &str) -> String {
    let cleaned: String = s
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    if cleaned.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(true) {
        format!("_{cleaned}")
    } else {
        cleaned
    }
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else if c == '-' || c == ' ' {
            result.push('_');
        } else {
            result.push(c);
        }
    }
    result
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize = true;
    for c in s.chars() {
        if c == '_' || c == '-' || c == ' ' {
            capitalize = true;
        } else if capitalize {
            result.extend(c.to_uppercase());
            capitalize = false;
        } else {
            result.push(c);
        }
    }
    result
}

fn to_camel_case(s: &str) -> String {
    let pascal = to_pascal_case(s);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(c) => c.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn package_lowercases_domain_no_separators() {
        assert_eq!(sanitize_package("FulfillmentContext"), "fulfillmentcontext");
        assert_eq!(sanitize_package(""), "etdlgenerated");
    }

    #[test]
    fn pascal_and_camel_case() {
        assert_eq!(to_pascal_case("order_placed"), "OrderPlaced");
        assert_eq!(to_camel_case("OrderPlaced"), "orderPlaced");
    }

    #[test]
    fn in_operator_lowers_to_native_contains_helper() {
        let cond = ecel::parse_condition(
            "message.payload.status in [\"PAID\", \"AUTHORIZED\"]",
        )
        .unwrap();
        let code = condition_to_go_code(&cond);
        assert!(code.contains("mustContains("), "got: {code}");
        assert!(code.contains("\"PAID\""));
    }

    #[test]
    fn matches_operator_lowers_to_native_matches_helper() {
        let cond = ecel::parse_condition(
            "message.payload.reference matches \"^ORD-[0-9]{8}$\"",
        )
        .unwrap();
        let code = condition_to_go_code(&cond);
        assert!(code.contains("mustMatches("), "got: {code}");
    }

    #[test]
    fn comparison_uses_pascal_case_field_access() {
        let cond = ecel::parse_condition("message.payload.amount >= 10000").unwrap();
        let code = condition_to_go_code(&cond);
        assert_eq!(code, "message.Payload.Amount >= 10000");
    }
}
