/* AUTOGENERATED by cbindgen from etdl-runtime-ffi's src/lib.rs — DO NOT EDIT.
 * Regenerated on every `cargo build -p etdl-runtime-ffi`.
 *
 * This is the one stable ABI surface every ETDL language target (Java, Go,
 * .NET, Python via ctypes, ...) binds to. See docs/architecture/targets.md.
 */


#ifndef ETDL_RUNTIME_FFI_H
#define ETDL_RUNTIME_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Bumped only when an existing exported function's signature or semantics
 * change incompatibly. Additive changes (new functions) do not require a
 * bump. A language binding should call [`etdl_runtime_abi_version`] at
 * startup and refuse to run (or warn loudly) against an unexpected major
 * version, rather than silently misinterpreting the ABI.
 *
 * `2`: [`etdl_branch_monitor_record_branch`] gained a `node_id` parameter
 * (fixes multiple barriers sharing one handle being mis-attributed to
 * whichever id the handle was created with — see its doc comment).
 */
#define ETDL_RUNTIME_ABI_VERSION 2

#define ETDL_OK 0

#define ETDL_ERR_NULL_HANDLE -1

#define ETDL_ERR_INVALID_ARG -2

/**
 * Returned by an `etdl_exporter_*_install` function when this library was
 * built without the matching `exporter-*` Cargo feature. The function
 * still exists (a stable, unconditional symbol set — no
 * `dlsym`/`GetProcAddress` probing required by callers); it just reports
 * that clearly instead of doing anything.
 */
#define ETDL_ERR_NOT_COMPILED_IN -3

#define ETDL_ERR_PANIC -99

/**
 * [`etdl_retry_policy_execute`]-specific outcomes (distinct range so a
 * caller can't confuse them with the general status codes above).
 */
#define ETDL_RETRY_OK 0

#define ETDL_RETRY_EXHAUSTED 1

#define ETDL_RETRY_FATAL 2

#define ETDL_RETRY_INVALID_ARG -2

/**
 * Opaque handle wrapping a real `etdl_core::BranchMonitor` — the same
 * type generated Rust code has always used. See the module-level
 * "Ownership model" section: create one per event-tree invocation, free
 * it with [`etdl_branch_monitor_free`] when that invocation completes.
 */
typedef struct EtdlBranchMonitor EtdlBranchMonitor;

typedef struct EtdlRetryPolicy EtdlRetryPolicy;

/**
 * The `etdl-runtime-ffi` crate (semver) version, as a static, null-terminated
 * UTF-8 C string. Distinct from [`etdl_runtime_abi_version`]: this is for
 * diagnostics/logging, not compatibility checks. Do not free the result —
 * it has static lifetime.
 */
const char *etdl_runtime_version(void);

/**
 * See [`ETDL_RUNTIME_ABI_VERSION`].
 */
uint32_t etdl_runtime_abi_version(void);

/**
 * Returns the last error message set on the *calling thread*, as an owned
 * string the caller must release with [`etdl_string_free`], or `NULL` if
 * no function called from this thread has failed yet. Reading it does not
 * clear it — the next failing call on this thread overwrites it.
 */
char *etdl_last_error_message(void);

/**
 * Frees a string previously returned by this crate (currently only
 * [`etdl_last_error_message`]). Passing any other pointer, or freeing the
 * same pointer twice, is undefined behavior — same contract as C's
 * `free()`. A `NULL` argument is a documented no-op.
 */
void etdl_string_free(char *s);

/**
 * Registers (or, with `NULL`, clears) a process-wide log callback invoked
 * for runtime events worth surfacing in the host language's own logging —
 * currently, failures recorded via [`etdl_branch_monitor_record_failure`].
 * A panic inside the callback is caught here and never propagates.
 */
void etdl_set_log_callback(void (*callback)(int32_t level, const char *message));

struct EtdlBranchMonitor *etdl_branch_monitor_new(const char *node_id);

/**
 * Frees a handle created by [`etdl_branch_monitor_new`]. `NULL` is a
 * documented no-op.
 */
void etdl_branch_monitor_free(struct EtdlBranchMonitor *handle);

/**
 * Records that `outcome` was taken at `node_id`, with `probability`.
 * `node_id` lets one handle be reused across several barriers in the same
 * call and still attribute each one's SLA window independently — pass the
 * specific barrier's own id, not necessarily the id `handle` was created
 * with. Returns [`ETDL_OK`] or a negative error code.
 */
int32_t etdl_branch_monitor_record_branch(struct EtdlBranchMonitor *handle,
                                          const char *node_id,
                                          const char *outcome,
                                          double probability);

/**
 * Records that `operation_id` completed successfully (its
 * `onFailureProbabilitySource`-linked probability, if any, in
 * `probability` — set `has_probability = false` when the operation has no
 * linked fault tree). Must be paired with
 * [`etdl_branch_monitor_record_failure`] on the same `operation_id` for
 * SLA accounting to reflect the operation's true success/failure mix, not
 * only its failures — see `etdl_core::BranchMonitor::record_success`'s
 * doc comment for why.
 */
int32_t etdl_branch_monitor_record_success(struct EtdlBranchMonitor *handle,
                                           const char *operation_id,
                                           double probability,
                                           bool has_probability);

/**
 * Records that `operation_id` failed with `error_message`. Also invokes
 * the registered log callback (see [`etdl_set_log_callback`]) with
 * `level = 2`.
 */
int32_t etdl_branch_monitor_record_failure(struct EtdlBranchMonitor *handle,
                                           const char *operation_id,
                                           const char *error_message,
                                           double probability,
                                           bool has_probability);

/**
 * `strategy`: `0` = fixed, `1` = exponential. Any other value is an
 * error (returns `NULL`; see [`etdl_last_error_message`]).
 */
struct EtdlRetryPolicy *etdl_retry_policy_new(uint32_t max_attempts,
                                              uint64_t backoff_ms,
                                              int32_t strategy);

void etdl_retry_policy_free(struct EtdlRetryPolicy *handle);

/**
 * The authoritative backoff delay (ms) before `attempt` (0-indexed),
 * exactly the formula `etdl_core::RetryPolicy::execute` itself uses —
 * exposed directly so a target's native retry loop (or
 * [`etdl_retry_policy_execute`] below) never re-derives it.
 */
uint64_t etdl_retry_policy_delay_ms(const struct EtdlRetryPolicy *handle, uint32_t attempt);

/**
 * Runs the authoritative ETDL retry loop: calls `callback` up to
 * `max_attempts` times (as configured on `handle`), sleeping
 * [`etdl_retry_policy_delay_ms`] between attempts, stopping on the first
 * success or fatal result. See [`EtdlRetryCallback`] for the callback
 * contract. `out_attempts_used` (if non-null) receives how many attempts
 * were actually made.
 *
 * No per-attempt timeout is enforced here — see the module-level
 * "Ownership model" section for why; apply one natively around the
 * callback body on the language side if needed.
 *
 * Returns [`ETDL_RETRY_OK`], [`ETDL_RETRY_EXHAUSTED`] (every attempt
 * returned a retryable failure), [`ETDL_RETRY_FATAL`] (callback returned
 * negative, or panicked), or [`ETDL_RETRY_INVALID_ARG`] (null
 * handle/callback).
 */
int32_t etdl_retry_policy_execute(const struct EtdlRetryPolicy *handle,
                                  int32_t (*callback)(void *user_data, uint32_t attempt),
                                  void *user_data,
                                  uint32_t *out_attempts_used);

/**
 * ECEL `matches` (RE2-compatible regular expression). Returns `1` (match),
 * `0` (no match), or `-1` (invalid argument — see
 * [`etdl_last_error_message`]). An invalid regex pattern is treated as
 * "no match" (`0`), exactly like `etdl_core::condition::matches` itself,
 * not as an error.
 */
int32_t etdl_condition_matches(const char *value, const char *pattern);

/**
 * ECEL `in`. `needle_json` is a single JSON value; `haystack_json_array`
 * is a JSON array. Returns `1` (`needle` is an element of `haystack`),
 * `0` (it is not), or `-1` (invalid/unparseable JSON — see
 * [`etdl_last_error_message`]).
 */
int32_t etdl_condition_contains(const char *needle_json, const char *haystack_json_array);

/**
 * Starts the compiled-in Prometheus scrape endpoint at `bind_addr` (e.g.
 * `"127.0.0.1:9464"`, serving `/metrics`). Call once at startup, before
 * handling any messages. Returns [`ETDL_OK`], [`ETDL_ERR_INVALID_ARG`]
 * (null/invalid-UTF-8/unparseable address, or the exporter failed to
 * start), or [`ETDL_ERR_NOT_COMPILED_IN`] if this library was built
 * without the `exporter-prometheus` feature.
 */
int32_t etdl_exporter_prometheus_install(const char *bind_addr);

/**
 * Pushes observations to a Loki-compatible push API at `loki_url` (e.g.
 * `"http://localhost:3100"`). `labels_json` is a JSON object of string
 * labels attached to every pushed stream (e.g. `{"service":"payments"}`);
 * `NULL` or `"{}"` means no extra labels. Call once at startup, before
 * handling any messages — installs a fresh global `tracing` subscriber,
 * so do not call this if the host process already has its own. Returns
 * [`ETDL_OK`], [`ETDL_ERR_INVALID_ARG`] (null/invalid UTF-8/unparseable
 * URL or labels, or setup failed), or [`ETDL_ERR_NOT_COMPILED_IN`] if
 * this library was built without the `exporter-loki` feature.
 */
int32_t etdl_exporter_loki_install(const char *loki_url, const char *labels_json);

/**
 * Pushes metrics to an OTel Collector (or any OTLP/HTTP receiver) at
 * `endpoint` (e.g. `"http://localhost:4318"`) via the official
 * OpenTelemetry Rust SDK, over HTTP+protobuf. Call once at startup,
 * before handling any messages. Returns [`ETDL_OK`],
 * [`ETDL_ERR_INVALID_ARG`] (null/invalid UTF-8, or setup failed), or
 * [`ETDL_ERR_NOT_COMPILED_IN`] if this library was built without the
 * `exporter-otlp` feature.
 */
int32_t etdl_exporter_otlp_install(const char *endpoint);

#endif  /* ETDL_RUNTIME_FFI_H */
