//! The `dotnet` [`CodeGenerator`] target.
//!
//! Consumes the exact same validated [`EtlDocument`] + resolved fault-tree
//! probabilities + [`AsyncApiRegistry`] every other target consumes.
//! Nothing here re-parses `.etdl`, re-validates ECEL conditions, or
//! re-evaluates fault trees. Generated C# is a thin binding — modern
//! P/Invoke (`[LibraryImport]` + `[UnmanagedCallersOnly]`) to the same
//! compiled `etdl-runtime-ffi` C ABI the Java (`java.lang.foreign`) and
//! Python (`ctypes`) targets bind to — not a reimplementation of ETDL
//! semantics. See `docs/architecture/targets.md`.
//!
//! Building this crate never requires a .NET SDK — it only emits C#
//! source text (plus a minimal `.csproj`). A .NET SDK (8+, for
//! `LibraryImport`/`UnmanagedCallersOnly`) is needed only to *build and
//! run* the generated output, and `etdl-runtime-ffi`'s compiled shared
//! library is needed to run anything that touches
//! `BranchMonitor`/`RetryPolicy`/`Condition`.

use etdl_compiler::{CodeGenerator, Diagnostic, GeneratedFile};
use etdl_parser::ast::{
    BackoffStrategy as AstBackoffStrategy, ChannelRef, Condition, EtlDocument, EventTree,
    MessageRef, Node,
};
use etdl_parser::asyncapi::AsyncApiRegistry;
use etdl_parser::ecel;
use std::collections::BTreeMap;

pub struct DotnetCodeGenerator {
    pub version: String,
    /// C# namespace for document-specific output. `None` derives it
    /// (PascalCase) from `info.domain`.
    pub namespace: Option<String>,
}

impl Default for DotnetCodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl DotnetCodeGenerator {
    pub fn new() -> Self {
        DotnetCodeGenerator {
            version: env!("CARGO_PKG_VERSION").to_string(),
            namespace: None,
        }
    }

    fn resolve_namespace(&self, doc: &EtlDocument) -> String {
        if let Some(ref ns) = self.namespace {
            return ns.clone();
        }
        sanitize_namespace(&doc.info.domain)
    }
}

impl CodeGenerator for DotnetCodeGenerator {
    fn target_name(&self) -> &'static str {
        "dotnet"
    }

    fn generate_all(
        &self,
        doc: &EtlDocument,
        fault_tree_probs: &BTreeMap<String, f64>,
        registry: &AsyncApiRegistry,
        stem: &str,
        _diagnostics: &mut Vec<Diagnostic>,
    ) -> Result<Vec<GeneratedFile>, String> {
        let namespace = self.resolve_namespace(doc);
        let project_name = to_pascal_case(&sanitize_ident(stem));

        let mut files = runtime_files();
        files.push(GeneratedFile::new(
            format!("{project_name}.csproj"),
            generate_csproj(&project_name),
        ));

        let message_refs = collect_message_refs(doc);
        if !message_refs.is_empty() {
            let mut messages_file = String::new();
            messages_file.push_str("// AUTOGENERATED BY ETDL COMPILER - DO NOT EDIT DIRECTLY\n\n");
            messages_file.push_str("using System.Collections.Generic;\n");
            messages_file.push_str("using System.Text.Json.Serialization;\n\n");
            messages_file.push_str(&format!("namespace {namespace};\n\n"));
            for (type_name, msg_ref) in &message_refs {
                let value = registry
                    .resolve_message(doc, msg_ref)
                    .map_err(|e| format!("resolving message for '{type_name}': {e}"))?;
                messages_file.push_str(&generate_message_record(type_name, &value));
            }
            files.push(GeneratedFile::new(
                format!("{namespace}/Messages.cs"),
                messages_file,
            ));
        }

        for tree in doc.event_trees.values() {
            let tree_id = tree_id_of(doc, tree);
            let iface_name = format!("I{}Handlers", to_pascal_case(&sanitize_ident(tree_id)));
            let handler_methods = collect_handler_methods(tree);
            let msg_type = ref_to_type_name(&tree.initiating_event.message);
            files.push(GeneratedFile::new(
                format!("{namespace}/{iface_name}.cs"),
                generate_handlers_interface(&namespace, &iface_name, &msg_type, &handler_methods),
            ));
        }

        let workflow = generate_workflow_class(doc, &namespace, &project_name, fault_tree_probs)?;
        files.push(GeneratedFile::new(
            format!("{namespace}/{project_name}Workflow.cs"),
            workflow,
        ));

        Ok(files)
    }
}

fn tree_id_of<'a>(doc: &'a EtlDocument, tree: &EventTree) -> &'a str {
    doc.event_trees
        .iter()
        .find(|(_, t)| std::ptr::eq(*t, tree))
        .map(|(id, _)| id.as_str())
        .unwrap_or("Tree")
}

fn generate_csproj(project_name: &str) -> String {
    format!(
        r#"<!-- AUTOGENERATED BY ETDL COMPILER - safe to edit (project settings only; add your own
     developer .cs files anywhere under this directory and the SDK's default
     globbing picks them up automatically).

     TargetFramework: LibraryImport/UnmanagedCallersOnly (the P/Invoke
     mechanism etdl.runtime uses) need .NET 7+; net9.0 is picked because
     targeting any framework version other than the installed SDK's own
     major version makes the SDK download that version's runtime pack from
     NuGet on first build (slow, and unnecessary here). Change this if your
     SDK is a different major version. -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>{project_name}</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
"#
    )
}

// ---------------------------------------------------------------------
// Fixed, document-independent runtime (`Etdl/Runtime/*.cs`)
// ---------------------------------------------------------------------

fn runtime_files() -> Vec<GeneratedFile> {
    vec![
        GeneratedFile::new("Etdl/Runtime/WorkflowError.cs", WORKFLOW_ERROR_CS),
        GeneratedFile::new("Etdl/Runtime/IPublisher.cs", IPUBLISHER_CS),
        GeneratedFile::new("Etdl/Runtime/BackoffStrategy.cs", BACKOFF_STRATEGY_CS),
        GeneratedFile::new("Etdl/Runtime/NativeMethods.cs", NATIVE_METHODS_CS),
        GeneratedFile::new("Etdl/Runtime/BranchMonitor.cs", BRANCH_MONITOR_CS),
        GeneratedFile::new("Etdl/Runtime/RetryPolicy.cs", RETRY_POLICY_CS),
        GeneratedFile::new("Etdl/Runtime/Condition.cs", CONDITION_CS),
    ]
}

const WORKFLOW_ERROR_CS: &str = r#"// Read-only ETDL runtime. DO NOT EDIT DIRECTLY.
namespace Etdl.Runtime;

using System;

/// <summary>Raised for a retryable operation failure. Analogous to the
/// Rust target's <c>etdl_core::WorkflowError</c> and the Java/Python
/// targets' <c>WorkflowError</c>.</summary>
public class WorkflowError : Exception
{
    public WorkflowError(string message) : base(message) { }

    public WorkflowError(string message, Exception inner) : base(message, inner) { }
}
"#;

const IPUBLISHER_CS: &str = r#"// Read-only ETDL runtime. DO NOT EDIT DIRECTLY.
namespace Etdl.Runtime;

/// <summary>The stable API boundary generated orchestration code calls
/// into for a <c>consequence: send</c> (core spec Section 5.5.3). A
/// developer supplies a concrete implementation (wiring it to a real
/// broker/client and handling serialization however fits their stack);
/// generated code never depends on a specific transport or JSON library.
/// Application integration, not ETDL runtime machinery — unlike
/// <see cref="BranchMonitor"/>/<see cref="RetryPolicy"/>/
/// <see cref="Condition"/>, there is no native binding here.</summary>
public interface IPublisher
{
    void Publish(string channel, object? payload);
}
"#;

const BACKOFF_STRATEGY_CS: &str = r#"// Read-only ETDL runtime. DO NOT EDIT DIRECTLY.
namespace Etdl.Runtime;

/// <summary>Mirrors <c>etdl-runtime-ffi</c>'s <c>strategy</c> parameter
/// encoding exactly: <c>0</c> = fixed, <c>1</c> = exponential.</summary>
public enum BackoffStrategy
{
    Fixed = 0,
    Exponential = 1,
}
"#;

/// The native-binding layer: modern P/Invoke (`[LibraryImport]`, source
/// generated at compile time — no runtime reflection) to every function
/// `etdl-runtime-ffi/src/lib.rs` exports. `BranchMonitor`/`RetryPolicy`/
/// `Condition` are thin facades over this; nothing here re-implements
/// ETDL semantics.
const NATIVE_METHODS_CS: &str = r#"// Read-only ETDL runtime. DO NOT EDIT DIRECTLY.
//
// Binds to `libetdl_runtime_ffi`/`etdl_runtime_ffi.dll` (built from the
// `etdl-runtime-ffi` Rust crate — see `docs/architecture/targets.md`) via
// .NET's modern source-generated P/Invoke (`LibraryImport`, .NET 7+).
//
// Library resolution: .NET's default native-library resolver already
// applies the platform's naming convention (`lib*.so`/`.dylib` vs
// `*.dll`) to a bare name like "etdl_runtime_ffi" and searches the app's
// base directory plus the platform's standard shared-library search
// path. `ETDL_RUNTIME_LIBRARY` (an environment variable, checked first)
// overrides that with an explicit absolute path, via
// `NativeLibrary.SetDllImportResolver`.
namespace Etdl.Runtime;

using System;
using System.Reflection;
using System.Runtime.InteropServices;

internal static partial class NativeMethods
{
    private const string LibraryName = "etdl_runtime_ffi";

    // Mirrors etdl-runtime-ffi's ETDL_OK / ETDL_ERR_* / ETDL_RETRY_* constants exactly.
    public const int Ok = 0;
    public const int ErrNullHandle = -1;
    public const int ErrInvalidArg = -2;
    public const int RetryOk = 0;
    public const int RetryExhausted = 1;
    public const int RetryFatal = 2;

    static NativeMethods()
    {
        NativeLibrary.SetDllImportResolver(typeof(NativeMethods).Assembly, Resolve);
    }

    private static IntPtr Resolve(string libraryName, Assembly assembly, DllImportSearchPath? searchPath)
    {
        if (libraryName != LibraryName)
        {
            return IntPtr.Zero;
        }
        string? explicitPath = Environment.GetEnvironmentVariable("ETDL_RUNTIME_LIBRARY");
        if (explicitPath != null)
        {
            return NativeLibrary.Load(explicitPath);
        }
        return IntPtr.Zero; // fall through to the default resolution strategy
    }

    [LibraryImport(LibraryName)]
    public static partial uint etdl_runtime_abi_version();

    [LibraryImport(LibraryName)]
    public static partial nint etdl_last_error_message();

    [LibraryImport(LibraryName)]
    public static partial void etdl_string_free(nint s);

    [LibraryImport(LibraryName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint etdl_branch_monitor_new(string nodeId);

    [LibraryImport(LibraryName)]
    public static partial void etdl_branch_monitor_free(nint handle);

    [LibraryImport(LibraryName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial int etdl_branch_monitor_record_branch(nint handle, string outcome, double probability);

    [LibraryImport(LibraryName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial int etdl_branch_monitor_record_success(
        nint handle, string operationId, double probability, [MarshalAs(UnmanagedType.I1)] bool hasProbability);

    [LibraryImport(LibraryName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial int etdl_branch_monitor_record_failure(
        nint handle, string operationId, string errorMessage, double probability,
        [MarshalAs(UnmanagedType.I1)] bool hasProbability);

    [LibraryImport(LibraryName)]
    public static partial nint etdl_retry_policy_new(uint maxAttempts, ulong backoffMs, int strategy);

    [LibraryImport(LibraryName)]
    public static partial void etdl_retry_policy_free(nint handle);

    [LibraryImport(LibraryName)]
    public static partial ulong etdl_retry_policy_delay_ms(nint handle, uint attempt);

    [LibraryImport(LibraryName)]
    public static unsafe partial int etdl_retry_policy_execute(
        nint handle, delegate* unmanaged[Cdecl]<nint, uint, int> callback, nint userData, uint* outAttemptsUsed);

    [LibraryImport(LibraryName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial int etdl_condition_matches(string value, string pattern);

    [LibraryImport(LibraryName, StringMarshalling = StringMarshalling.Utf8)]
    public static partial int etdl_condition_contains(string needleJson, string haystackJson);

    /// <summary>Reads and frees the calling thread's last native error
    /// message.</summary>
    public static string LastError()
    {
        nint ptr = etdl_last_error_message();
        if (ptr == 0)
        {
            return "(no further detail available from the native runtime)";
        }
        string message = Marshal.PtrToStringUTF8(ptr) ?? "(invalid UTF-8 from native runtime)";
        etdl_string_free(ptr);
        return message;
    }
}
"#;

/// The C# analog of `etdl_core::BranchMonitor` — not a reimplementation:
/// every method is a direct call into the same `BranchMonitor` the Rust
/// target's generated code has always used, via `etdl-runtime-ffi`.
const BRANCH_MONITOR_CS: &str = r#"// Read-only ETDL runtime. DO NOT EDIT DIRECTLY.
//
// Thin facade over the native `etdl_core::BranchMonitor` (via
// `etdl-runtime-ffi`). Owns one native handle; always use with `using`
// (generated orchestration code always does) so
// `etdl_branch_monitor_free` runs deterministically.
namespace Etdl.Runtime;

using System;

public sealed class BranchMonitor : IDisposable
{
    private readonly nint _handle;
    private bool _disposed;

    public BranchMonitor(string nodeId)
    {
        _handle = NativeMethods.etdl_branch_monitor_new(nodeId);
        if (_handle == 0)
        {
            throw new InvalidOperationException($"etdl_branch_monitor_new failed: {NativeMethods.LastError()}");
        }
    }

    public void RecordBranch(string outcome, double probability)
    {
        int rc = NativeMethods.etdl_branch_monitor_record_branch(_handle, outcome, probability);
        Check(rc, nameof(RecordBranch));
    }

    /// <summary><paramref name="probability"/> may be <c>null</c> when the
    /// operation has no linked fault tree.</summary>
    public void RecordSuccess(string operationId, double? probability)
    {
        int rc = NativeMethods.etdl_branch_monitor_record_success(
            _handle, operationId, probability ?? 0.0, probability.HasValue);
        Check(rc, nameof(RecordSuccess));
    }

    /// <summary><paramref name="probability"/> may be <c>null</c> when the
    /// operation has no linked fault tree.</summary>
    public void RecordFailure(string operationId, Exception error, double? probability)
    {
        int rc = NativeMethods.etdl_branch_monitor_record_failure(
            _handle, operationId, error.Message ?? string.Empty, probability ?? 0.0, probability.HasValue);
        Check(rc, nameof(RecordFailure));
    }

    private static void Check(int rc, string call)
    {
        if (rc != NativeMethods.Ok)
        {
            throw new InvalidOperationException($"{call} failed (code {rc}): {NativeMethods.LastError()}");
        }
    }

    public void Dispose()
    {
        if (!_disposed)
        {
            _disposed = true;
            NativeMethods.etdl_branch_monitor_free(_handle);
        }
    }
}
"#;

/// The C# analog of `etdl_core::retry::RetryPolicy` — the attempt-count
/// and backoff *sequence* are computed once, in Rust
/// (`etdl_retry_policy_execute`'s native loop), via an
/// `[UnmanagedCallersOnly]` trampoline bound to `op` through a
/// `GCHandle`-pinned context object (the standard .NET idiom for passing
/// managed state through a static native callback). Per-attempt timeout
/// enforcement stays here (see `docs/architecture/targets.md`'s
/// "Ownership model": no FFI boundary can safely cancel foreign code
/// mid-flight) — note a .NET `Task` cannot be forcibly killed either, so a
/// "timed out" attempt's task still runs to completion in the background;
/// only the *retry loop* moves on.
const RETRY_POLICY_CS: &str = r#"// Read-only ETDL runtime. DO NOT EDIT DIRECTLY.
//
// Thin facade over the native `etdl_core::RetryPolicy` (via
// `etdl-runtime-ffi`'s callback-driven `etdl_retry_policy_execute`). Owns
// one native handle; always use with `using`.
namespace Etdl.Runtime;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading.Tasks;

public sealed class RetryPolicy : IDisposable
{
    private readonly nint _handle;
    private bool _disposed;

    public RetryPolicy(uint maxAttempts, ulong backoffMs, BackoffStrategy strategy)
    {
        _handle = NativeMethods.etdl_retry_policy_new(maxAttempts, backoffMs, (int)strategy);
        if (_handle == 0)
        {
            throw new InvalidOperationException($"etdl_retry_policy_new failed: {NativeMethods.LastError()}");
        }
    }

    /// <summary>Per-<see cref="Execute"/>-call state, reached from the
    /// static <see cref="NativeTrampoline"/> through a pinned
    /// <see cref="GCHandle"/> passed as the native call's <c>userData</c>.
    /// <c>op</c>'s own exception (checked <see cref="WorkflowError"/> or
    /// any other exception) is caught here — it never crosses the native
    /// call, exactly as the FFI boundary requires.</summary>
    private sealed class Trampoline
    {
        public required Func<object?> Op;
        public double? TimeoutSeconds;
        public object? Result;
        public WorkflowError? CheckedError;
        public Exception? UncheckedError;

        public int Invoke(uint attempt)
        {
            try
            {
                Task<object?> task = Task.Run(Op);
                bool completed = TimeoutSeconds is double t
                    ? task.Wait(TimeSpan.FromSeconds(t))
                    : task.Wait(-1);
                if (!completed)
                {
                    CheckedError = new WorkflowError($"operation timed out after {TimeoutSeconds}s");
                    return 1;
                }
                Result = task.Result;
                return 0;
            }
            catch (AggregateException ae) when (ae.InnerException is WorkflowError we)
            {
                CheckedError = we;
                return 1;
            }
            catch (AggregateException ae)
            {
                UncheckedError = ae.InnerException ?? ae;
                return -1;
            }
            catch (Exception e)
            {
                UncheckedError = e;
                return -1;
            }
        }
    }

    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    private static int NativeTrampoline(nint userData, uint attempt)
    {
        GCHandle gcHandle = GCHandle.FromIntPtr(userData);
        var trampoline = (Trampoline)gcHandle.Target!;
        return trampoline.Invoke(attempt);
    }

    public unsafe T? Execute<T>(Func<T> op, double? timeoutSeconds = null)
    {
        var trampoline = new Trampoline { Op = () => op(), TimeoutSeconds = timeoutSeconds };
        GCHandle gcHandle = GCHandle.Alloc(trampoline);
        try
        {
            uint attemptsUsed;
            int rc = NativeMethods.etdl_retry_policy_execute(
                _handle, &NativeTrampoline, GCHandle.ToIntPtr(gcHandle), &attemptsUsed);

            if (rc == NativeMethods.RetryOk)
            {
                return (T?)trampoline.Result;
            }
            if (trampoline.UncheckedError != null)
            {
                throw trampoline.UncheckedError;
            }
            if (trampoline.CheckedError != null)
            {
                throw trampoline.CheckedError;
            }
            string kind = rc == NativeMethods.RetryFatal ? "retry failed fatally" : "retry exhausted";
            throw new WorkflowError($"{kind}: {NativeMethods.LastError()}");
        }
        finally
        {
            gcHandle.Free();
        }
    }

    public void Dispose()
    {
        if (!_disposed)
        {
            _disposed = true;
            NativeMethods.etdl_retry_policy_free(_handle);
        }
    }
}
"#;

/// The C# analog of `etdl_core::condition::{contains, matches}` — ECEL
/// `in`/`matches` semantics stay in Rust; this facade only marshals
/// values to/from the JSON text `etdl_condition_contains` expects, using
/// `System.Text.Json` (part of the .NET base class library — no NuGet
/// package needed).
const CONDITION_CS: &str = r#"// Read-only ETDL runtime. DO NOT EDIT DIRECTLY.
//
// ECEL (core spec Section 6) `in`/`matches` operators lower to these
// helpers, delegating to the native `etdl_core::condition` module (via
// `etdl-runtime-ffi`) — so a `matches` regex or an `in` membership check
// behaves byte-for-byte identically no matter which target (Rust, Java,
// Python, Go, .NET) evaluates it.
namespace Etdl.Runtime;

using System;
using System.Collections.Generic;
using System.Text.Json;

public static class Condition
{
    public static bool Matches(string? value, string pattern)
    {
        int rc = NativeMethods.etdl_condition_matches(value ?? string.Empty, pattern);
        if (rc < 0)
        {
            throw new ArgumentException($"etdl_condition_matches: {NativeMethods.LastError()}");
        }
        return rc == 1;
    }

    public static bool Contains<T>(IEnumerable<T>? haystack, T needle)
    {
        string needleJson = JsonSerializer.Serialize(needle);
        string haystackJson = JsonSerializer.Serialize(haystack ?? Array.Empty<T>());
        int rc = NativeMethods.etdl_condition_contains(needleJson, haystackJson);
        if (rc < 0)
        {
            throw new ArgumentException($"etdl_condition_contains: {NativeMethods.LastError()}");
        }
        return rc == 1;
    }
}
"#;

// ---------------------------------------------------------------------
// Message records
// ---------------------------------------------------------------------

fn collect_message_refs(doc: &EtlDocument) -> BTreeMap<String, MessageRef> {
    let mut refs: BTreeMap<String, MessageRef> = BTreeMap::new();
    let note = |m: &MessageRef, refs: &mut BTreeMap<String, MessageRef>| {
        let name = ref_to_type_name(m);
        refs.entry(name).or_insert_with(|| m.clone());
    };

    for tree in doc.event_trees.values() {
        note(&tree.initiating_event.message, &mut refs);
        for node in tree.nodes.values() {
            match node {
                Node::Operation(op) => {
                    if let Some(ref m) = op.emits {
                        note(m, &mut refs);
                    }
                }
                Node::Consequence(cons) => {
                    if let Some(ref m) = cons.message {
                        note(m, &mut refs);
                    }
                }
                _ => {}
            }
        }
    }

    if let Some(ref fault_trees) = doc.fault_trees {
        for ft in fault_trees.values() {
            if let Some(ref m) = ft.top_event.message {
                note(m, &mut refs);
            }
            for be in ft.basic_events.values() {
                if let Some(ref m) = be.message {
                    note(m, &mut refs);
                }
            }
        }
    }

    refs
}

fn ref_to_type_name(msg_ref: &MessageRef) -> String {
    let pointer = match msg_ref {
        MessageRef::External(r) => &r.pointer,
        MessageRef::Internal(r) => &r.pointer,
    };
    extract_last_segment(pointer)
}

fn extract_last_segment(pointer: &str) -> String {
    let last = pointer.rsplit('/').next().unwrap_or("Unknown");
    to_pascal_case(last)
}

fn generate_message_record(type_name: &str, message: &serde_json::Value) -> String {
    let payload_type_name = format!("{type_name}Payload");
    let payload_schema = message.get("payload").cloned().unwrap_or(serde_json::Value::Null);

    let mut nested = String::new();
    let payload_cs_type = schema_to_dotnet_type(&payload_type_name, &payload_schema, &mut nested, false);

    let mut out = String::new();
    out.push_str(&nested);
    out.push_str(&format!(
        "public sealed record {type_name}({payload_cs_type} Payload, IReadOnlyDictionary<string, object>? Headers = null);\n\n"
    ));
    out
}

/// C# analog of the Rust/Java/Python targets' struct/record/dataclass
/// generators. Like the Python target (and unlike Java's `record`, whose
/// fields have no such constraint), a C# positional `record`'s
/// constructor parameters without a default must all precede parameters
/// *with* a default — so required fields are always emitted before
/// optional ones, regardless of the schema's own property order.
fn generate_record_from_schema(name: &str, schema: &serde_json::Value, output: &mut String) {
    let Some(properties) = schema.get("properties").and_then(|p| p.as_object()) else {
        return;
    };

    let required: std::collections::BTreeSet<&str> = schema
        .get("required")
        .and_then(|r| r.as_array())
        .map(|arr| arr.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default();

    let mut nested = String::new();
    let mut required_params = Vec::new();
    let mut optional_params = Vec::new();

    for (field_name, field_schema) in properties {
        let pascal = to_pascal_case(field_name);
        let nested_type_name = format!("{name}{pascal}");
        let is_required = required.contains(field_name.as_str());
        let cs_type = schema_to_dotnet_type(&nested_type_name, field_schema, &mut nested, !is_required);
        let json_attr = if pascal != *field_name {
            format!("[property: JsonPropertyName(\"{field_name}\")] ")
        } else {
            String::new()
        };
        if is_required {
            required_params.push(format!("{json_attr}{cs_type} {pascal}"));
        } else {
            optional_params.push(format!("{json_attr}{cs_type} {pascal} = default"));
        }
    }

    let mut params = required_params;
    params.extend(optional_params);

    output.push_str(&nested);
    output.push_str(&format!("public sealed record {name}({});\n\n", params.join(", ")));
}

fn schema_to_dotnet_type(
    candidate_name: &str,
    schema: &serde_json::Value,
    nested: &mut String,
    nullable: bool,
) -> String {
    let base = match schema.get("type").and_then(|t| t.as_str()) {
        Some("string") => "string".to_string(),
        Some("integer") => "long".to_string(),
        Some("number") => "double".to_string(),
        Some("boolean") => "bool".to_string(),
        Some("array") => {
            let item_type = match schema.get("items") {
                Some(items_schema) => schema_to_dotnet_type(
                    &format!("{candidate_name}Item"),
                    items_schema,
                    nested,
                    true,
                ),
                None => "object".to_string(),
            };
            return format!("IReadOnlyList<{item_type}>{}", if nullable { "?" } else { "" });
        }
        Some("object") => {
            if schema.get("properties").is_some() {
                generate_record_from_schema(candidate_name, schema, nested);
                candidate_name.to_string()
            } else {
                return format!(
                    "IReadOnlyDictionary<string, object>{}",
                    if nullable { "?" } else { "" }
                );
            }
        }
        _ => "object".to_string(),
    };
    if nullable {
        format!("{base}?")
    } else {
        base
    }
}

// ---------------------------------------------------------------------
// Handler interfaces (one per event tree — the user-editable boundary)
// ---------------------------------------------------------------------

fn collect_handler_methods(tree: &EventTree) -> Vec<String> {
    let mut seen = std::collections::BTreeSet::new();
    let mut methods = Vec::new();
    for node in tree.nodes.values() {
        if let Node::Operation(op) = node {
            let name = to_pascal_case(&op.handler);
            if seen.insert(name.clone()) {
                methods.push(name);
            }
        }
    }
    methods
}

fn generate_handlers_interface(namespace: &str, iface_name: &str, msg_type: &str, methods: &[String]) -> String {
    let mut out = String::new();
    out.push_str("// AUTOGENERATED BY ETDL COMPILER - DO NOT EDIT DIRECTLY\n");
    out.push_str("// Implement this interface in your own (never regenerated) class; the\n");
    out.push_str("// generated orchestration calls through it and never the other way around.\n");
    out.push_str(&format!("namespace {namespace};\n\n"));
    out.push_str(&format!("public interface {iface_name}\n{{\n"));
    for method in methods {
        out.push_str(&format!("    object? {method}({msg_type} message);\n"));
    }
    out.push_str("}\n");
    out
}

// ---------------------------------------------------------------------
// Workflow orchestration class
// ---------------------------------------------------------------------

fn generate_workflow_class(
    doc: &EtlDocument,
    namespace: &str,
    project_name: &str,
    fault_tree_probs: &BTreeMap<String, f64>,
) -> Result<String, String> {
    let mut out = String::new();
    out.push_str("// AUTOGENERATED BY ETDL COMPILER - DO NOT EDIT DIRECTLY\n\n");
    out.push_str("using Etdl.Runtime;\n");
    out.push_str("using System.Linq;\n\n");
    out.push_str(&format!("namespace {namespace};\n\n"));
    out.push_str(&format!("public static class {project_name}Workflow\n{{\n"));

    out.push_str(&generate_fault_tree_constants(doc, fault_tree_probs));

    for tree in doc.event_trees.values() {
        let method = generate_event_tree_method(doc, tree, fault_tree_probs)?;
        out.push_str(&method);
        out.push('\n');
    }

    out.push_str("}\n");
    Ok(out)
}

fn generate_fault_tree_constants(doc: &EtlDocument, fault_tree_probs: &BTreeMap<String, f64>) -> String {
    let mut output = String::new();
    for tree in doc.event_trees.values() {
        for (node_id, node) in &tree.nodes {
            if let Node::Operation(op) = node {
                if let Some(ref ps) = op.on_failure_probability_source {
                    if let Some((ft_id, prob)) = find_fault_tree_prob(ps, fault_tree_probs) {
                        output.push_str(&format!(
                            "    // Computed from faultTrees.{ft_id}.topEvent at build time (Section 5.16)\n"
                        ));
                        let const_name = to_pascal_case(&format!("{node_id}_failure_probability"));
                        output.push_str(&format!(
                            "    public const double {const_name} = {prob:.6};\n\n"
                        ));
                    }
                }
            }
        }
    }
    output
}

fn find_fault_tree_prob(
    ps: &etdl_parser::ast::InternalRef,
    fault_tree_probs: &BTreeMap<String, f64>,
) -> Option<(String, f64)> {
    let ft_id = extract_ft_id(&ps.pointer);
    fault_tree_probs.get(&ft_id).map(|&v| (ft_id.clone(), v))
}

fn extract_ft_id(pointer: &str) -> String {
    pointer
        .trim_start_matches("#/faultTrees/")
        .trim_end_matches("/topEvent")
        .to_string()
}

fn generate_event_tree_method(
    doc: &EtlDocument,
    tree: &EventTree,
    fault_tree_probs: &BTreeMap<String, f64>,
) -> Result<String, String> {
    let mut out = String::new();

    let tree_id = tree_id_of(doc, tree);
    let iface_name = format!("I{}Handlers", to_pascal_case(&sanitize_ident(tree_id)));
    let method_name = format!("Handle{}", to_pascal_case(&sanitize_ident(&tree.initiating_event.id)));
    let msg_type = ref_to_type_name(&tree.initiating_event.message);

    out.push_str(&format!(
        "    public static void {method_name}({msg_type} message, IPublisher publisher, {iface_name} handlers)\n    {{\n"
    ));

    let first_barrier = find_first_barrier(tree);
    let monitor_name = first_barrier.map(to_camel_case).unwrap_or_else(|| "monitor".to_string());
    out.push_str(&format!(
        "        using var {monitor_name} = new BranchMonitor(\"{}\");\n\n",
        first_barrier.unwrap_or("root")
    ));

    let start_node_id = &tree.initiating_event.next;
    let body = generate_node_code(doc, tree, start_node_id, 2, fault_tree_probs, &monitor_name)?;
    out.push_str(&body);

    out.push_str("    }\n");
    Ok(out)
}

fn find_first_barrier(tree: &EventTree) -> Option<&str> {
    let mut current = &tree.initiating_event.next;
    loop {
        match tree.nodes.get(current.as_str()) {
            Some(Node::Barrier(_)) => return Some(current.as_str()),
            Some(Node::Operation(op)) => current = &op.next,
            Some(Node::Consequence(_)) => return None,
            None => return None,
        }
    }
}

fn generate_node_code(
    doc: &EtlDocument,
    tree: &EventTree,
    node_id: &str,
    depth: usize,
    fault_tree_probs: &BTreeMap<String, f64>,
    monitor_name: &str,
) -> Result<String, String> {
    let node = tree
        .nodes
        .get(node_id)
        .ok_or_else(|| format!("node '{node_id}' not found"))?;

    match node {
        Node::Barrier(barrier) => {
            generate_barrier_code(tree, node_id, barrier, depth, doc, fault_tree_probs, monitor_name)
        }
        Node::Operation(op) => {
            generate_operation_code(tree, node_id, op, depth, doc, fault_tree_probs, monitor_name)
        }
        Node::Consequence(cons) => generate_consequence_code(cons, depth),
    }
}

fn generate_barrier_code(
    tree: &EventTree,
    node_id: &str,
    barrier: &etdl_parser::ast::Barrier,
    depth: usize,
    doc: &EtlDocument,
    fault_tree_probs: &BTreeMap<String, f64>,
    monitor_name: &str,
) -> Result<String, String> {
    let indent = "    ".repeat(depth);
    let mut output = String::new();

    for (i, branch) in barrier.branches.iter().enumerate() {
        let is_default = branch.condition == Condition::Default;
        if i == 0 {
            if is_default {
                emit_branch_record(&indent, monitor_name, branch, node_id, fault_tree_probs, &mut output);
                let body = generate_node_code(doc, tree, &branch.next, depth + 1, fault_tree_probs, monitor_name)?;
                output.push_str(&body);
            } else {
                let cond = condition_to_dotnet_code(&branch.condition);
                output.push_str(&format!("{indent}if ({cond})\n{indent}{{\n"));
                emit_branch_record(&format!("{indent}    "), monitor_name, branch, node_id, fault_tree_probs, &mut output);
                let body = generate_node_code(doc, tree, &branch.next, depth + 1, fault_tree_probs, monitor_name)?;
                output.push_str(&body);
                output.push_str(&format!("{indent}}}"));
            }
        } else if is_default {
            output.push_str(&format!("\n{indent}else\n{indent}{{\n"));
            emit_branch_record(&format!("{indent}    "), monitor_name, branch, node_id, fault_tree_probs, &mut output);
            let body = generate_node_code(doc, tree, &branch.next, depth + 1, fault_tree_probs, monitor_name)?;
            output.push_str(&body);
            output.push_str(&format!("{indent}}}\n"));
        } else {
            let cond = condition_to_dotnet_code(&branch.condition);
            output.push_str(&format!("\n{indent}else if ({cond})\n{indent}{{\n"));
            emit_branch_record(&format!("{indent}    "), monitor_name, branch, node_id, fault_tree_probs, &mut output);
            let body = generate_node_code(doc, tree, &branch.next, depth + 1, fault_tree_probs, monitor_name)?;
            output.push_str(&body);
            output.push_str(&format!("{indent}}}"));
        }
    }

    if !barrier.branches.is_empty() && barrier.branches.last().unwrap().condition != Condition::Default {
        output.push('\n');
    }

    Ok(output)
}

fn emit_branch_record(
    indent: &str,
    monitor_name: &str,
    branch: &etdl_parser::ast::Branch,
    node_id: &str,
    fault_tree_probs: &BTreeMap<String, f64>,
    output: &mut String,
) {
    if let Some(p) = get_branch_prob(branch, node_id, fault_tree_probs) {
        output.push_str(&format!(
            "{indent}{monitor_name}.RecordBranch(\"{}\", {p:.6});\n",
            branch.outcome
        ));
    }
}

fn get_branch_prob(
    branch: &etdl_parser::ast::Branch,
    _node_id: &str,
    fault_tree_probs: &BTreeMap<String, f64>,
) -> Option<f64> {
    if let Some(ref ps) = branch.probability_source {
        let ft_id = extract_ft_id(&ps.pointer);
        return fault_tree_probs.get(&ft_id).copied();
    }
    branch.effective_probability()
}

fn generate_operation_code(
    tree: &EventTree,
    node_id: &str,
    op: &etdl_parser::ast::Operation,
    depth: usize,
    doc: &EtlDocument,
    fault_tree_probs: &BTreeMap<String, f64>,
    monitor_name: &str,
) -> Result<String, String> {
    let indent = "    ".repeat(depth);
    let mut output = String::new();

    let handler_name = to_pascal_case(&op.handler);
    let timeout_s = op.timeout_ms.unwrap_or(5000) as f64 / 1000.0;

    output.push_str(&format!("{indent}try\n{indent}{{\n"));
    // `using var retry = ...;` is a declaration, not a block — unlike
    // Java's try-with-resources, it doesn't nest the rest of the try body
    // one level deeper, so `body_depth` is `depth + 1` whether or not this
    // operation has a retry policy.
    let body_depth = depth + 1;
    if let Some(ref retry) = op.retry_policy {
        let strategy = match retry.backoff_strategy.as_ref().unwrap_or(&AstBackoffStrategy::Fixed) {
            AstBackoffStrategy::Exponential => "BackoffStrategy.Exponential",
            AstBackoffStrategy::Fixed => "BackoffStrategy.Fixed",
        };
        output.push_str(&format!(
            "{indent}    using var retry = new RetryPolicy({}, {}, {strategy});\n",
            retry.max_attempts, retry.backoff_ms
        ));
        output.push_str(&format!(
            "{indent}    var _result = retry.Execute(() => handlers.{handler_name}(message), timeoutSeconds: {timeout_s});\n"
        ));
    } else {
        output.push_str(&format!(
            "{indent}    var _result = handlers.{handler_name}(message);\n"
        ));
    }

    if op.on_failure.is_some() {
        if let Some(ref ps) = op.on_failure_probability_source {
            let const_name = to_pascal_case(&format!("{node_id}_failure_probability"));
            let prob_exists = find_fault_tree_prob(ps, fault_tree_probs).is_some();
            let indent2 = "    ".repeat(body_depth);
            if prob_exists {
                output.push_str(&format!(
                    "{indent2}{monitor_name}.RecordSuccess(\"{node_id}\", {const_name});\n"
                ));
            } else {
                output.push_str(&format!(
                    "{indent2}{monitor_name}.RecordSuccess(\"{node_id}\", null);\n"
                ));
            }
        }
    }

    let next_node = tree.nodes.get(&op.next);
    match next_node {
        Some(Node::Consequence(cons)) => {
            emit_send(cons, "_result", &"    ".repeat(body_depth), &mut output);
        }
        Some(_) => {
            let body = generate_node_code(doc, tree, &op.next, body_depth, fault_tree_probs, monitor_name)?;
            output.push_str(&body);
        }
        None => {}
    }

    output.push_str(&format!("{indent}}}\n{indent}catch (WorkflowError err)\n{indent}{{\n"));

    if let Some(ref ps) = op.on_failure_probability_source {
        let const_name = to_pascal_case(&format!("{node_id}_failure_probability"));
        let prob_exists = find_fault_tree_prob(ps, fault_tree_probs).is_some();
        if prob_exists {
            output.push_str(&format!(
                "{indent}    {monitor_name}.RecordFailure(\"{node_id}\", err, {const_name});\n"
            ));
        } else {
            output.push_str(&format!(
                "{indent}    {monitor_name}.RecordFailure(\"{node_id}\", err, null);\n"
            ));
        }
    } else {
        output.push_str(&format!(
            "{indent}    {monitor_name}.RecordFailure(\"{node_id}\", err, null);\n"
        ));
    }

    if let Some(ref on_failure_id) = op.on_failure {
        match tree.nodes.get(on_failure_id) {
            Some(Node::Consequence(cons)) => {
                emit_send(cons, "message", &format!("{indent}    "), &mut output);
            }
            _ => {
                let body = generate_node_code(doc, tree, on_failure_id, depth + 1, fault_tree_probs, monitor_name)?;
                output.push_str(&body);
            }
        }
    } else {
        output.push_str(&format!("{indent}    throw;\n"));
    }

    output.push_str(&format!("{indent}}}\n"));

    Ok(output)
}

fn emit_send(cons: &etdl_parser::ast::Consequence, payload_expr: &str, indent: &str, output: &mut String) {
    if let etdl_parser::ast::ConsequenceOperation::Send = cons.consequence_operation {
        if let Some(ref channel_ref) = cons.channel {
            let channel_name = channel_ref_name(channel_ref);
            output.push_str(&format!(
                "{indent}publisher.Publish(\"{channel_name}\", {payload_expr});\n"
            ));
        }
    }
}

fn generate_consequence_code(cons: &etdl_parser::ast::Consequence, depth: usize) -> Result<String, String> {
    let indent = "    ".repeat(depth);
    let mut output = String::new();

    if let etdl_parser::ast::ConsequenceOperation::Send = cons.consequence_operation {
        if let Some(ref channel_ref) = cons.channel {
            let channel_name = channel_ref_name(channel_ref);
            output.push_str(&format!("{indent}publisher.Publish(\"{channel_name}\", message);\n"));
        }
    }

    Ok(output)
}

fn channel_ref_name(channel_ref: &ChannelRef) -> String {
    match channel_ref {
        ChannelRef::External(ext_ref) => extract_last_segment(&ext_ref.pointer),
        ChannelRef::Bare(name) => name.clone(),
    }
}

// ---------------------------------------------------------------------
// ECEL condition -> C#
// ---------------------------------------------------------------------

fn condition_to_dotnet_code(condition: &Condition) -> String {
    match condition {
        Condition::Default => "true".to_string(),
        Condition::Comparison(cmp) => {
            use ecel::Comparator as C;
            match cmp.op {
                C::In => {
                    let left = path_or_literal(&cmp.left);
                    let right = array_or_literal(&cmp.right);
                    format!("Condition.Contains({right}, {left})")
                }
                C::Matches => {
                    let left = operand_to_path_expr_or_literal(&cmp.left);
                    let right = literal_to_val_str(&literal_of(&cmp.right));
                    format!("Condition.Matches({left}, {right})")
                }
                _ => {
                    let (left_path, has_wildcard) = build_path_expression(&cmp.left);
                    let right = operand_to_val_str(&cmp.right);
                    let op = comparator_str(&cmp.op);

                    if has_wildcard {
                        // The message parameter is the tree's concrete
                        // generated `record` type, so `path_prefix` is
                        // already a strongly-typed `IReadOnlyList<T>` —
                        // `.All(...)` needs no cast, unlike a `dynamic`
                        // field would.
                        format!(
                            "{}.All(item => item{} {} {})",
                            left_path.path_prefix, left_path.remaining_path, op, right
                        )
                    } else {
                        let l = if left_path.path_prefix.is_empty() && left_path.remaining_path.is_empty() {
                            operand_to_val_str(&cmp.left)
                        } else {
                            left_path.path_prefix + &left_path.remaining_path
                        };
                        let r = if right.is_empty() { operand_to_path_expr(&cmp.right) } else { right };
                        format!("{l} {op} {r}")
                    }
                }
            }
        }
    }
}

fn path_or_literal(operand: &ecel::Operand) -> String {
    match operand {
        ecel::Operand::Path(_) => operand_to_path_expr(operand),
        ecel::Operand::Literal(lit) => literal_to_val_str(lit),
    }
}

fn array_or_literal(operand: &ecel::Operand) -> String {
    match operand {
        ecel::Operand::Path(_) => operand_to_path_expr(operand),
        ecel::Operand::Literal(lit) => literal_to_val_str(lit),
    }
}

fn operand_to_path_expr_or_literal(operand: &ecel::Operand) -> String {
    match operand {
        ecel::Operand::Path(_) => operand_to_path_expr(operand),
        ecel::Operand::Literal(lit) => literal_to_val_str(lit),
    }
}

fn literal_of(operand: &ecel::Operand) -> ecel::Literal {
    match operand {
        ecel::Operand::Literal(lit) => lit.clone(),
        ecel::Operand::Path(_) => ecel::Literal::String(String::new()),
    }
}

struct PathParts {
    path_prefix: String,
    remaining_path: String,
}

/// C# analog of the other targets' path-expression builder. Segments
/// render as PascalCase property access (`.Field`) — C# convention for
/// generated `record` properties — and `Index`/`QuotedKey` segments
/// render as `[...]` subscripting (works on both `IReadOnlyList<T>` and
/// `IReadOnlyDictionary<string, object>` directly).
fn build_path_expression(operand: &ecel::Operand) -> (PathParts, bool) {
    match operand {
        ecel::Operand::Path(path_expr) => {
            let segments = &path_expr.segments;
            let mut pre_wildcard = Vec::new();
            let mut post_wildcard = Vec::new();
            let mut has_wildcard = false;

            for (i, seg) in segments.iter().enumerate() {
                if i == 0 {
                    continue;
                }
                if has_wildcard {
                    post_wildcard.push(seg.clone());
                } else if matches!(seg, ecel::PathSegment::Wildcard) {
                    has_wildcard = true;
                } else {
                    pre_wildcard.push(seg.clone());
                }
            }

            let mut prefix = String::from("message");
            for seg in &pre_wildcard {
                append_segment(&mut prefix, seg);
            }

            let mut suffix = String::new();
            for seg in &post_wildcard {
                append_segment(&mut suffix, seg);
            }

            (
                PathParts { path_prefix: prefix, remaining_path: suffix },
                has_wildcard,
            )
        }
        ecel::Operand::Literal(_) => (
            PathParts { path_prefix: String::new(), remaining_path: String::new() },
            false,
        ),
    }
}

fn append_segment(out: &mut String, seg: &ecel::PathSegment) {
    match seg {
        ecel::PathSegment::Field(name) => {
            out.push('.');
            out.push_str(&to_pascal_case(name));
        }
        ecel::PathSegment::Index(idx) => {
            out.push_str(&format!("[{idx}]"));
        }
        ecel::PathSegment::QuotedKey(name) => {
            out.push_str(&format!("[\"{name}\"]"));
        }
        _ => {}
    }
}

fn operand_to_path_expr(operand: &ecel::Operand) -> String {
    match operand {
        ecel::Operand::Path(path) => {
            let mut out = String::from("message");
            for seg in path.segments.iter().skip(1) {
                if matches!(seg, ecel::PathSegment::Wildcard) {
                    continue;
                }
                append_segment(&mut out, seg);
            }
            out
        }
        ecel::Operand::Literal(_) => String::new(),
    }
}

fn operand_to_val_str(operand: &ecel::Operand) -> String {
    match operand {
        ecel::Operand::Path(_) => "".to_string(),
        ecel::Operand::Literal(lit) => literal_to_val_str(lit),
    }
}

fn literal_to_val_str(lit: &ecel::Literal) -> String {
    match lit {
        ecel::Literal::Number(n) => n.to_string(),
        ecel::Literal::String(s) => format!("\"{s}\""),
        ecel::Literal::Bool(b) => if *b { "true".to_string() } else { "false".to_string() },
        ecel::Literal::Null => "null".to_string(),
        ecel::Literal::Array(items) => {
            let inner: Vec<String> = items.iter().map(literal_to_val_str).collect();
            format!("new[] {{ {} }}", inner.join(", "))
        }
    }
}

fn comparator_str(op: &ecel::Comparator) -> &str {
    match op {
        ecel::Comparator::Eq => "==",
        ecel::Comparator::Neq => "!=",
        ecel::Comparator::Gte => ">=",
        ecel::Comparator::Lte => "<=",
        ecel::Comparator::Gt => ">",
        ecel::Comparator::Lt => "<",
        ecel::Comparator::In => "in",
        ecel::Comparator::Matches => "matches",
    }
}

// ---------------------------------------------------------------------
// Naming helpers
// ---------------------------------------------------------------------

fn sanitize_namespace(domain: &str) -> String {
    let pascal = to_pascal_case(domain);
    if pascal.is_empty() {
        "EtdlGenerated".to_string()
    } else {
        pascal
    }
}

fn sanitize_ident(s: &str) -> String {
    let cleaned: String = s
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    if cleaned.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(true) {
        format!("_{cleaned}")
    } else {
        cleaned
    }
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize = true;
    for c in s.chars() {
        if c == '_' || c == '-' || c == ' ' {
            capitalize = true;
        } else if capitalize {
            result.extend(c.to_uppercase());
            capitalize = false;
        } else {
            result.push(c);
        }
    }
    result
}

fn to_camel_case(s: &str) -> String {
    let pascal = to_pascal_case(s);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(c) => c.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn namespace_pascal_cases_domain() {
        assert_eq!(sanitize_namespace("FulfillmentContext"), "FulfillmentContext");
        assert_eq!(sanitize_namespace(""), "EtdlGenerated");
    }

    #[test]
    fn pascal_and_camel_case() {
        assert_eq!(to_pascal_case("order_placed"), "OrderPlaced");
        assert_eq!(to_camel_case("OrderPlaced"), "orderPlaced");
    }

    #[test]
    fn in_operator_lowers_to_native_contains_call() {
        let cond = ecel::parse_condition(
            "message.payload.status in [\"PAID\", \"AUTHORIZED\"]",
        )
        .unwrap();
        let code = condition_to_dotnet_code(&cond);
        assert!(code.contains("Condition.Contains("), "got: {code}");
        assert!(code.contains("\"PAID\""));
    }

    #[test]
    fn matches_operator_lowers_to_native_matches_call() {
        let cond = ecel::parse_condition(
            "message.payload.reference matches \"^ORD-[0-9]{8}$\"",
        )
        .unwrap();
        let code = condition_to_dotnet_code(&cond);
        assert!(code.contains("Condition.Matches("), "got: {code}");
    }

    #[test]
    fn comparison_uses_pascal_case_property_access() {
        let cond = ecel::parse_condition("message.payload.amount >= 10000").unwrap();
        let code = condition_to_dotnet_code(&cond);
        assert_eq!(code, "message.Payload.Amount >= 10000");
    }
}
